<?php

namespace EqualSite\Events\Value;

use Exception;
use stdClass;

// This is an autogenerated file:AuditCompleted

class AuditCompleted {
    private AuditCompletedPayload $payload; // json:payload Required
    private int $timestamp; // json:timestamp Required
    private AuditCompletedType $type; // json:type Required
    private string $version; // json:version Required

    /**
     * @param AuditCompletedPayload $payload
     * @param int $timestamp
     * @param AuditCompletedType $type
     * @param string $version
     */
    public function __construct(AuditCompletedPayload $payload, int $timestamp, AuditCompletedType $type, string $version) {
        $this->payload = $payload;
        $this->timestamp = $timestamp;
        $this->type = $type;
        $this->version = $version;
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return AuditCompletedPayload
     */
    public static function fromPayload(stdClass $value): AuditCompletedPayload {
        return AuditCompletedPayload::from($value); /*class*/
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toPayload(): stdClass {
        if (AuditCompleted::validatePayload($this->payload))  {
            return $this->payload->to(); /*class*/
        }
        throw new Exception('never get to this AuditCompleted::payload');
    }

    /**
     * @param AuditCompletedPayload
     * @return bool
     * @throws Exception
     */
    public static function validatePayload(AuditCompletedPayload $value): bool {
        $value->validate();
        return true;
    }

    /**
     * @throws Exception
     * @return AuditCompletedPayload
     */
    public function getPayload(): AuditCompletedPayload {
        if (AuditCompleted::validatePayload($this->payload))  {
            return $this->payload;
        }
        throw new Exception('never get to getPayload AuditCompleted::payload');
    }

    /**
     * @return AuditCompletedPayload
     */
    public static function samplePayload(): AuditCompletedPayload {
        return AuditCompletedPayload::sample(); /*31:payload*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromTimestamp(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toTimestamp(): int {
        if (AuditCompleted::validateTimestamp($this->timestamp))  {
            return $this->timestamp; /*int*/
        }
        throw new Exception('never get to this AuditCompleted::timestamp');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateTimestamp(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditCompleted::timestamp");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getTimestamp(): int {
        if (AuditCompleted::validateTimestamp($this->timestamp))  {
            return $this->timestamp;
        }
        throw new Exception('never get to getTimestamp AuditCompleted::timestamp');
    }

    /**
     * @return int
     */
    public static function sampleTimestamp(): int {
        return 32; /*32:timestamp*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return AuditCompletedType
     */
    public static function fromType(string $value): AuditCompletedType {
        return AuditCompletedType::from($value); /*enum*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toType(): string {
        if (AuditCompleted::validateType($this->type))  {
            return AuditCompletedType::to($this->type); /*enum*/
        }
        throw new Exception('never get to this AuditCompleted::type');
    }

    /**
     * @param AuditCompletedType
     * @return bool
     * @throws Exception
     */
    public static function validateType(AuditCompletedType $value): bool {
        AuditCompletedType::to($value);
        return true;
    }

    /**
     * @throws Exception
     * @return AuditCompletedType
     */
    public function getType(): AuditCompletedType {
        if (AuditCompleted::validateType($this->type))  {
            return $this->type;
        }
        throw new Exception('never get to getType AuditCompleted::type');
    }

    /**
     * @return AuditCompletedType
     */
    public static function sampleType(): AuditCompletedType {
        return AuditCompletedType::sample(); /*enum*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromVersion(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toVersion(): string {
        if (AuditCompleted::validateVersion($this->version))  {
            return $this->version; /*string*/
        }
        throw new Exception('never get to this AuditCompleted::version');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateVersion(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditCompleted::version");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getVersion(): string {
        if (AuditCompleted::validateVersion($this->version))  {
            return $this->version;
        }
        throw new Exception('never get to getVersion AuditCompleted::version');
    }

    /**
     * @return string
     */
    public static function sampleVersion(): string {
        return 'AuditCompleted::version::34'; /*34:version*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditCompleted::validatePayload($this->payload)
        || AuditCompleted::validateTimestamp($this->timestamp)
        || AuditCompleted::validateType($this->type)
        || AuditCompleted::validateVersion($this->version);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'payload'} = $this->toPayload();
        $out->{'timestamp'} = $this->toTimestamp();
        $out->{'type'} = $this->toType();
        $out->{'version'} = $this->toVersion();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditCompleted
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditCompleted {
        return new AuditCompleted(
         AuditCompleted::fromPayload($obj->{'payload'})
        ,AuditCompleted::fromTimestamp($obj->{'timestamp'})
        ,AuditCompleted::fromType($obj->{'type'})
        ,AuditCompleted::fromVersion($obj->{'version'})
        );
    }

    /**
     * @return AuditCompleted
     */
    public static function sample(): AuditCompleted {
        return new AuditCompleted(
         AuditCompleted::samplePayload()
        ,AuditCompleted::sampleTimestamp()
        ,AuditCompleted::sampleType()
        ,AuditCompleted::sampleVersion()
        );
    }
}

// This is an autogenerated file:AuditCompletedPayload

class AuditCompletedPayload {
    private string $auditId; // json:auditId Required
    private ?string $crawlerFinishedAt; // json:crawlerFinishedAt Optional
    private float $crawlerRuntimeMillis; // json:crawlerRuntimeMillis Required
    private ?string $crawlerStartedAt; // json:crawlerStartedAt Optional
    private stdClass $errors; // json:errors Required
    private float $requestMaxDurationMillis; // json:requestMaxDurationMillis Required
    private float $requestMinDurationMillis; // json:requestMinDurationMillis Required
    private int $requestsFailed; // json:requestsFailed Required
    private float $requestsFailedPerMinute; // json:requestsFailedPerMinute Required
    private int $requestsFinished; // json:requestsFinished Required
    private float $requestsFinishedPerMinute; // json:requestsFinishedPerMinute Required
    private int $requestsRetries; // json:requestsRetries Required
    private stdClass $requestsWithStatusCode; // json:requestsWithStatusCode Required
    private float $requestTotalFailedDurationMillis; // json:requestTotalFailedDurationMillis Required
    private float $requestTotalFinishedDurationMillis; // json:requestTotalFinishedDurationMillis Required
    private stdClass $retryErrors; // json:retryErrors Required
    private ?string $statsPersistedAt; // json:statsPersistedAt Optional

    /**
     * @param string $auditId
     * @param string|null $crawlerFinishedAt
     * @param float $crawlerRuntimeMillis
     * @param string|null $crawlerStartedAt
     * @param stdClass $errors
     * @param float $requestMaxDurationMillis
     * @param float $requestMinDurationMillis
     * @param int $requestsFailed
     * @param float $requestsFailedPerMinute
     * @param int $requestsFinished
     * @param float $requestsFinishedPerMinute
     * @param int $requestsRetries
     * @param stdClass $requestsWithStatusCode
     * @param float $requestTotalFailedDurationMillis
     * @param float $requestTotalFinishedDurationMillis
     * @param stdClass $retryErrors
     * @param string|null $statsPersistedAt
     */
    public function __construct(string $auditId, ?string $crawlerFinishedAt, float $crawlerRuntimeMillis, ?string $crawlerStartedAt, stdClass $errors, float $requestMaxDurationMillis, float $requestMinDurationMillis, int $requestsFailed, float $requestsFailedPerMinute, int $requestsFinished, float $requestsFinishedPerMinute, int $requestsRetries, stdClass $requestsWithStatusCode, float $requestTotalFailedDurationMillis, float $requestTotalFinishedDurationMillis, stdClass $retryErrors, ?string $statsPersistedAt) {
        $this->auditId = $auditId;
        $this->crawlerFinishedAt = $crawlerFinishedAt;
        $this->crawlerRuntimeMillis = $crawlerRuntimeMillis;
        $this->crawlerStartedAt = $crawlerStartedAt;
        $this->errors = $errors;
        $this->requestMaxDurationMillis = $requestMaxDurationMillis;
        $this->requestMinDurationMillis = $requestMinDurationMillis;
        $this->requestsFailed = $requestsFailed;
        $this->requestsFailedPerMinute = $requestsFailedPerMinute;
        $this->requestsFinished = $requestsFinished;
        $this->requestsFinishedPerMinute = $requestsFinishedPerMinute;
        $this->requestsRetries = $requestsRetries;
        $this->requestsWithStatusCode = $requestsWithStatusCode;
        $this->requestTotalFailedDurationMillis = $requestTotalFailedDurationMillis;
        $this->requestTotalFinishedDurationMillis = $requestTotalFinishedDurationMillis;
        $this->retryErrors = $retryErrors;
        $this->statsPersistedAt = $statsPersistedAt;
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromAuditId(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toAuditId(): string {
        if (AuditCompletedPayload::validateAuditId($this->auditId))  {
            return $this->auditId; /*string*/
        }
        throw new Exception('never get to this AuditCompletedPayload::auditId');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateAuditId(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditCompletedPayload::auditId");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getAuditId(): string {
        if (AuditCompletedPayload::validateAuditId($this->auditId))  {
            return $this->auditId;
        }
        throw new Exception('never get to getAuditId AuditCompletedPayload::auditId');
    }

    /**
     * @return string
     */
    public static function sampleAuditId(): string {
        return 'AuditCompletedPayload::auditId::31'; /*31:auditId*/
    }

    /**
     * @param ?string $value
     * @throws Exception
     * @return ?string
     */
    public static function fromCrawlerFinishedAt(?string $value): ?string {
        if (!is_null($value)) {
            return $value; /*string*/
        } else {
            return  null;
        }
    }

    /**
     * @throws Exception
     * @return ?string
     */
    public function toCrawlerFinishedAt(): ?string {
        if (AuditCompletedPayload::validateCrawlerFinishedAt($this->crawlerFinishedAt))  {
            if (!is_null($this->crawlerFinishedAt)) {
                return $this->crawlerFinishedAt; /*string*/
            } else {
                return  null;
            }
        }
        throw new Exception('never get to this AuditCompletedPayload::crawlerFinishedAt');
    }

    /**
     * @param string|null
     * @return bool
     * @throws Exception
     */
    public static function validateCrawlerFinishedAt(?string $value): bool {
        if (!is_null($value)) {
            if (!is_string($value)) {
                throw new Exception("Attribute Error:AuditCompletedPayload::crawlerFinishedAt");
            }
        }
        return true;
    }

    /**
     * @throws Exception
     * @return ?string
     */
    public function getCrawlerFinishedAt(): ?string {
        if (AuditCompletedPayload::validateCrawlerFinishedAt($this->crawlerFinishedAt))  {
            return $this->crawlerFinishedAt;
        }
        throw new Exception('never get to getCrawlerFinishedAt AuditCompletedPayload::crawlerFinishedAt');
    }

    /**
     * @return ?string
     */
    public static function sampleCrawlerFinishedAt(): ?string {
        return 'AuditCompletedPayload::crawlerFinishedAt::32'; /*32:crawlerFinishedAt*/
    }

    /**
     * @param float $value
     * @throws Exception
     * @return float
     */
    public static function fromCrawlerRuntimeMillis(float $value): float {
        return $value; /*float*/
    }

    /**
     * @throws Exception
     * @return float
     */
    public function toCrawlerRuntimeMillis(): float {
        if (AuditCompletedPayload::validateCrawlerRuntimeMillis($this->crawlerRuntimeMillis))  {
            return $this->crawlerRuntimeMillis; /*float*/
        }
        throw new Exception('never get to this AuditCompletedPayload::crawlerRuntimeMillis');
    }

    /**
     * @param float
     * @return bool
     * @throws Exception
     */
    public static function validateCrawlerRuntimeMillis(float $value): bool {
        if (!is_float($value) && !is_int($value)) {
            throw new Exception("Attribute Error:AuditCompletedPayload::crawlerRuntimeMillis");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return float
     */
    public function getCrawlerRuntimeMillis(): float {
        if (AuditCompletedPayload::validateCrawlerRuntimeMillis($this->crawlerRuntimeMillis))  {
            return $this->crawlerRuntimeMillis;
        }
        throw new Exception('never get to getCrawlerRuntimeMillis AuditCompletedPayload::crawlerRuntimeMillis');
    }

    /**
     * @return float
     */
    public static function sampleCrawlerRuntimeMillis(): float {
        return 33.033; /*33:crawlerRuntimeMillis*/
    }

    /**
     * @param ?string $value
     * @throws Exception
     * @return ?string
     */
    public static function fromCrawlerStartedAt(?string $value): ?string {
        if (!is_null($value)) {
            return $value; /*string*/
        } else {
            return  null;
        }
    }

    /**
     * @throws Exception
     * @return ?string
     */
    public function toCrawlerStartedAt(): ?string {
        if (AuditCompletedPayload::validateCrawlerStartedAt($this->crawlerStartedAt))  {
            if (!is_null($this->crawlerStartedAt)) {
                return $this->crawlerStartedAt; /*string*/
            } else {
                return  null;
            }
        }
        throw new Exception('never get to this AuditCompletedPayload::crawlerStartedAt');
    }

    /**
     * @param string|null
     * @return bool
     * @throws Exception
     */
    public static function validateCrawlerStartedAt(?string $value): bool {
        if (!is_null($value)) {
            if (!is_string($value)) {
                throw new Exception("Attribute Error:AuditCompletedPayload::crawlerStartedAt");
            }
        }
        return true;
    }

    /**
     * @throws Exception
     * @return ?string
     */
    public function getCrawlerStartedAt(): ?string {
        if (AuditCompletedPayload::validateCrawlerStartedAt($this->crawlerStartedAt))  {
            return $this->crawlerStartedAt;
        }
        throw new Exception('never get to getCrawlerStartedAt AuditCompletedPayload::crawlerStartedAt');
    }

    /**
     * @return ?string
     */
    public static function sampleCrawlerStartedAt(): ?string {
        return 'AuditCompletedPayload::crawlerStartedAt::34'; /*34:crawlerStartedAt*/
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return stdClass
     */
    public static function fromErrors(stdClass $value): stdClass {
        $out = new stdClass();
        foreach ($value as $k => $v) {
            $out->$k = $v; /*any*/
        }
        return $out;
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toErrors(): stdClass {
        if (AuditCompletedPayload::validateErrors($this->errors))  {
            $out = new stdClass();
            foreach ($this->errors as $k => $v) {
                $out->$k = $v; /*any*/
            }
            return $out;
        }
        throw new Exception('never get to this AuditCompletedPayload::errors');
    }

    /**
     * @param stdClass
     * @return bool
     * @throws Exception
     */
    public static function validateErrors(stdClass $value): bool {
        foreach ($value as $k => $v) {
        }
        return true;
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function getErrors(): stdClass {
        if (AuditCompletedPayload::validateErrors($this->errors))  {
            return $this->errors;
        }
        throw new Exception('never get to getErrors AuditCompletedPayload::errors');
    }

    /**
     * @return stdClass
     */
    public static function sampleErrors(): stdClass {
        return  (function () {
            $out = new stdClass();
            $out->{'AuditCompletedPayload'} = 'AnyType::AuditCompletedPayload::errors::35';/*35:errors*/
            return $out;
        })(); /* 35:errors*/
    }

    /**
     * @param float $value
     * @throws Exception
     * @return float
     */
    public static function fromRequestMaxDurationMillis(float $value): float {
        return $value; /*float*/
    }

    /**
     * @throws Exception
     * @return float
     */
    public function toRequestMaxDurationMillis(): float {
        if (AuditCompletedPayload::validateRequestMaxDurationMillis($this->requestMaxDurationMillis))  {
            return $this->requestMaxDurationMillis; /*float*/
        }
        throw new Exception('never get to this AuditCompletedPayload::requestMaxDurationMillis');
    }

    /**
     * @param float
     * @return bool
     * @throws Exception
     */
    public static function validateRequestMaxDurationMillis(float $value): bool {
        if (!is_float($value) && !is_int($value)) {
            throw new Exception("Attribute Error:AuditCompletedPayload::requestMaxDurationMillis");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return float
     */
    public function getRequestMaxDurationMillis(): float {
        if (AuditCompletedPayload::validateRequestMaxDurationMillis($this->requestMaxDurationMillis))  {
            return $this->requestMaxDurationMillis;
        }
        throw new Exception('never get to getRequestMaxDurationMillis AuditCompletedPayload::requestMaxDurationMillis');
    }

    /**
     * @return float
     */
    public static function sampleRequestMaxDurationMillis(): float {
        return 36.036; /*36:requestMaxDurationMillis*/
    }

    /**
     * @param float $value
     * @throws Exception
     * @return float
     */
    public static function fromRequestMinDurationMillis(float $value): float {
        return $value; /*float*/
    }

    /**
     * @throws Exception
     * @return float
     */
    public function toRequestMinDurationMillis(): float {
        if (AuditCompletedPayload::validateRequestMinDurationMillis($this->requestMinDurationMillis))  {
            return $this->requestMinDurationMillis; /*float*/
        }
        throw new Exception('never get to this AuditCompletedPayload::requestMinDurationMillis');
    }

    /**
     * @param float
     * @return bool
     * @throws Exception
     */
    public static function validateRequestMinDurationMillis(float $value): bool {
        if (!is_float($value) && !is_int($value)) {
            throw new Exception("Attribute Error:AuditCompletedPayload::requestMinDurationMillis");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return float
     */
    public function getRequestMinDurationMillis(): float {
        if (AuditCompletedPayload::validateRequestMinDurationMillis($this->requestMinDurationMillis))  {
            return $this->requestMinDurationMillis;
        }
        throw new Exception('never get to getRequestMinDurationMillis AuditCompletedPayload::requestMinDurationMillis');
    }

    /**
     * @return float
     */
    public static function sampleRequestMinDurationMillis(): float {
        return 37.037; /*37:requestMinDurationMillis*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromRequestsFailed(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toRequestsFailed(): int {
        if (AuditCompletedPayload::validateRequestsFailed($this->requestsFailed))  {
            return $this->requestsFailed; /*int*/
        }
        throw new Exception('never get to this AuditCompletedPayload::requestsFailed');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateRequestsFailed(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditCompletedPayload::requestsFailed");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getRequestsFailed(): int {
        if (AuditCompletedPayload::validateRequestsFailed($this->requestsFailed))  {
            return $this->requestsFailed;
        }
        throw new Exception('never get to getRequestsFailed AuditCompletedPayload::requestsFailed');
    }

    /**
     * @return int
     */
    public static function sampleRequestsFailed(): int {
        return 38; /*38:requestsFailed*/
    }

    /**
     * @param float $value
     * @throws Exception
     * @return float
     */
    public static function fromRequestsFailedPerMinute(float $value): float {
        return $value; /*float*/
    }

    /**
     * @throws Exception
     * @return float
     */
    public function toRequestsFailedPerMinute(): float {
        if (AuditCompletedPayload::validateRequestsFailedPerMinute($this->requestsFailedPerMinute))  {
            return $this->requestsFailedPerMinute; /*float*/
        }
        throw new Exception('never get to this AuditCompletedPayload::requestsFailedPerMinute');
    }

    /**
     * @param float
     * @return bool
     * @throws Exception
     */
    public static function validateRequestsFailedPerMinute(float $value): bool {
        if (!is_float($value) && !is_int($value)) {
            throw new Exception("Attribute Error:AuditCompletedPayload::requestsFailedPerMinute");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return float
     */
    public function getRequestsFailedPerMinute(): float {
        if (AuditCompletedPayload::validateRequestsFailedPerMinute($this->requestsFailedPerMinute))  {
            return $this->requestsFailedPerMinute;
        }
        throw new Exception('never get to getRequestsFailedPerMinute AuditCompletedPayload::requestsFailedPerMinute');
    }

    /**
     * @return float
     */
    public static function sampleRequestsFailedPerMinute(): float {
        return 39.039; /*39:requestsFailedPerMinute*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromRequestsFinished(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toRequestsFinished(): int {
        if (AuditCompletedPayload::validateRequestsFinished($this->requestsFinished))  {
            return $this->requestsFinished; /*int*/
        }
        throw new Exception('never get to this AuditCompletedPayload::requestsFinished');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateRequestsFinished(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditCompletedPayload::requestsFinished");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getRequestsFinished(): int {
        if (AuditCompletedPayload::validateRequestsFinished($this->requestsFinished))  {
            return $this->requestsFinished;
        }
        throw new Exception('never get to getRequestsFinished AuditCompletedPayload::requestsFinished');
    }

    /**
     * @return int
     */
    public static function sampleRequestsFinished(): int {
        return 40; /*40:requestsFinished*/
    }

    /**
     * @param float $value
     * @throws Exception
     * @return float
     */
    public static function fromRequestsFinishedPerMinute(float $value): float {
        return $value; /*float*/
    }

    /**
     * @throws Exception
     * @return float
     */
    public function toRequestsFinishedPerMinute(): float {
        if (AuditCompletedPayload::validateRequestsFinishedPerMinute($this->requestsFinishedPerMinute))  {
            return $this->requestsFinishedPerMinute; /*float*/
        }
        throw new Exception('never get to this AuditCompletedPayload::requestsFinishedPerMinute');
    }

    /**
     * @param float
     * @return bool
     * @throws Exception
     */
    public static function validateRequestsFinishedPerMinute(float $value): bool {
        if (!is_float($value) && !is_int($value)) {
            throw new Exception("Attribute Error:AuditCompletedPayload::requestsFinishedPerMinute");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return float
     */
    public function getRequestsFinishedPerMinute(): float {
        if (AuditCompletedPayload::validateRequestsFinishedPerMinute($this->requestsFinishedPerMinute))  {
            return $this->requestsFinishedPerMinute;
        }
        throw new Exception('never get to getRequestsFinishedPerMinute AuditCompletedPayload::requestsFinishedPerMinute');
    }

    /**
     * @return float
     */
    public static function sampleRequestsFinishedPerMinute(): float {
        return 41.041; /*41:requestsFinishedPerMinute*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromRequestsRetries(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toRequestsRetries(): int {
        if (AuditCompletedPayload::validateRequestsRetries($this->requestsRetries))  {
            return $this->requestsRetries; /*int*/
        }
        throw new Exception('never get to this AuditCompletedPayload::requestsRetries');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateRequestsRetries(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditCompletedPayload::requestsRetries");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getRequestsRetries(): int {
        if (AuditCompletedPayload::validateRequestsRetries($this->requestsRetries))  {
            return $this->requestsRetries;
        }
        throw new Exception('never get to getRequestsRetries AuditCompletedPayload::requestsRetries');
    }

    /**
     * @return int
     */
    public static function sampleRequestsRetries(): int {
        return 42; /*42:requestsRetries*/
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return stdClass
     */
    public static function fromRequestsWithStatusCode(stdClass $value): stdClass {
        $out = new stdClass();
        foreach ($value as $k => $v) {
            $out->$k = $v; /*int*/
        }
        return $out;
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toRequestsWithStatusCode(): stdClass {
        if (AuditCompletedPayload::validateRequestsWithStatusCode($this->requestsWithStatusCode))  {
            $out = new stdClass();
            foreach ($this->requestsWithStatusCode as $k => $v) {
                $out->$k = $v; /*int*/
            }
            return $out;
        }
        throw new Exception('never get to this AuditCompletedPayload::requestsWithStatusCode');
    }

    /**
     * @param stdClass
     * @return bool
     * @throws Exception
     */
    public static function validateRequestsWithStatusCode(stdClass $value): bool {
        foreach ($value as $k => $v) {
            if (!is_integer($v)) {
                throw new Exception("Attribute Error:AuditCompletedPayload::requestsWithStatusCode");
            }
        }
        return true;
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function getRequestsWithStatusCode(): stdClass {
        if (AuditCompletedPayload::validateRequestsWithStatusCode($this->requestsWithStatusCode))  {
            return $this->requestsWithStatusCode;
        }
        throw new Exception('never get to getRequestsWithStatusCode AuditCompletedPayload::requestsWithStatusCode');
    }

    /**
     * @return stdClass
     */
    public static function sampleRequestsWithStatusCode(): stdClass {
        return  (function () {
            $out = new stdClass();
            $out->{'AuditCompletedPayload'} = 43; /*43:requestsWithStatusCode*/
            return $out;
        })(); /* 43:requestsWithStatusCode*/
    }

    /**
     * @param float $value
     * @throws Exception
     * @return float
     */
    public static function fromRequestTotalFailedDurationMillis(float $value): float {
        return $value; /*float*/
    }

    /**
     * @throws Exception
     * @return float
     */
    public function toRequestTotalFailedDurationMillis(): float {
        if (AuditCompletedPayload::validateRequestTotalFailedDurationMillis($this->requestTotalFailedDurationMillis))  {
            return $this->requestTotalFailedDurationMillis; /*float*/
        }
        throw new Exception('never get to this AuditCompletedPayload::requestTotalFailedDurationMillis');
    }

    /**
     * @param float
     * @return bool
     * @throws Exception
     */
    public static function validateRequestTotalFailedDurationMillis(float $value): bool {
        if (!is_float($value) && !is_int($value)) {
            throw new Exception("Attribute Error:AuditCompletedPayload::requestTotalFailedDurationMillis");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return float
     */
    public function getRequestTotalFailedDurationMillis(): float {
        if (AuditCompletedPayload::validateRequestTotalFailedDurationMillis($this->requestTotalFailedDurationMillis))  {
            return $this->requestTotalFailedDurationMillis;
        }
        throw new Exception('never get to getRequestTotalFailedDurationMillis AuditCompletedPayload::requestTotalFailedDurationMillis');
    }

    /**
     * @return float
     */
    public static function sampleRequestTotalFailedDurationMillis(): float {
        return 44.044; /*44:requestTotalFailedDurationMillis*/
    }

    /**
     * @param float $value
     * @throws Exception
     * @return float
     */
    public static function fromRequestTotalFinishedDurationMillis(float $value): float {
        return $value; /*float*/
    }

    /**
     * @throws Exception
     * @return float
     */
    public function toRequestTotalFinishedDurationMillis(): float {
        if (AuditCompletedPayload::validateRequestTotalFinishedDurationMillis($this->requestTotalFinishedDurationMillis))  {
            return $this->requestTotalFinishedDurationMillis; /*float*/
        }
        throw new Exception('never get to this AuditCompletedPayload::requestTotalFinishedDurationMillis');
    }

    /**
     * @param float
     * @return bool
     * @throws Exception
     */
    public static function validateRequestTotalFinishedDurationMillis(float $value): bool {
        if (!is_float($value) && !is_int($value)) {
            throw new Exception("Attribute Error:AuditCompletedPayload::requestTotalFinishedDurationMillis");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return float
     */
    public function getRequestTotalFinishedDurationMillis(): float {
        if (AuditCompletedPayload::validateRequestTotalFinishedDurationMillis($this->requestTotalFinishedDurationMillis))  {
            return $this->requestTotalFinishedDurationMillis;
        }
        throw new Exception('never get to getRequestTotalFinishedDurationMillis AuditCompletedPayload::requestTotalFinishedDurationMillis');
    }

    /**
     * @return float
     */
    public static function sampleRequestTotalFinishedDurationMillis(): float {
        return 45.045; /*45:requestTotalFinishedDurationMillis*/
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return stdClass
     */
    public static function fromRetryErrors(stdClass $value): stdClass {
        $out = new stdClass();
        foreach ($value as $k => $v) {
            $out->$k = $v; /*any*/
        }
        return $out;
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toRetryErrors(): stdClass {
        if (AuditCompletedPayload::validateRetryErrors($this->retryErrors))  {
            $out = new stdClass();
            foreach ($this->retryErrors as $k => $v) {
                $out->$k = $v; /*any*/
            }
            return $out;
        }
        throw new Exception('never get to this AuditCompletedPayload::retryErrors');
    }

    /**
     * @param stdClass
     * @return bool
     * @throws Exception
     */
    public static function validateRetryErrors(stdClass $value): bool {
        foreach ($value as $k => $v) {
        }
        return true;
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function getRetryErrors(): stdClass {
        if (AuditCompletedPayload::validateRetryErrors($this->retryErrors))  {
            return $this->retryErrors;
        }
        throw new Exception('never get to getRetryErrors AuditCompletedPayload::retryErrors');
    }

    /**
     * @return stdClass
     */
    public static function sampleRetryErrors(): stdClass {
        return  (function () {
            $out = new stdClass();
            $out->{'AuditCompletedPayload'} = 'AnyType::AuditCompletedPayload::retryErrors::46';/*46:retryErrors*/
            return $out;
        })(); /* 46:retryErrors*/
    }

    /**
     * @param ?string $value
     * @throws Exception
     * @return ?string
     */
    public static function fromStatsPersistedAt(?string $value): ?string {
        if (!is_null($value)) {
            return $value; /*string*/
        } else {
            return  null;
        }
    }

    /**
     * @throws Exception
     * @return ?string
     */
    public function toStatsPersistedAt(): ?string {
        if (AuditCompletedPayload::validateStatsPersistedAt($this->statsPersistedAt))  {
            if (!is_null($this->statsPersistedAt)) {
                return $this->statsPersistedAt; /*string*/
            } else {
                return  null;
            }
        }
        throw new Exception('never get to this AuditCompletedPayload::statsPersistedAt');
    }

    /**
     * @param string|null
     * @return bool
     * @throws Exception
     */
    public static function validateStatsPersistedAt(?string $value): bool {
        if (!is_null($value)) {
            if (!is_string($value)) {
                throw new Exception("Attribute Error:AuditCompletedPayload::statsPersistedAt");
            }
        }
        return true;
    }

    /**
     * @throws Exception
     * @return ?string
     */
    public function getStatsPersistedAt(): ?string {
        if (AuditCompletedPayload::validateStatsPersistedAt($this->statsPersistedAt))  {
            return $this->statsPersistedAt;
        }
        throw new Exception('never get to getStatsPersistedAt AuditCompletedPayload::statsPersistedAt');
    }

    /**
     * @return ?string
     */
    public static function sampleStatsPersistedAt(): ?string {
        return 'AuditCompletedPayload::statsPersistedAt::47'; /*47:statsPersistedAt*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditCompletedPayload::validateAuditId($this->auditId)
        || AuditCompletedPayload::validateCrawlerFinishedAt($this->crawlerFinishedAt)
        || AuditCompletedPayload::validateCrawlerRuntimeMillis($this->crawlerRuntimeMillis)
        || AuditCompletedPayload::validateCrawlerStartedAt($this->crawlerStartedAt)
        || AuditCompletedPayload::validateErrors($this->errors)
        || AuditCompletedPayload::validateRequestMaxDurationMillis($this->requestMaxDurationMillis)
        || AuditCompletedPayload::validateRequestMinDurationMillis($this->requestMinDurationMillis)
        || AuditCompletedPayload::validateRequestsFailed($this->requestsFailed)
        || AuditCompletedPayload::validateRequestsFailedPerMinute($this->requestsFailedPerMinute)
        || AuditCompletedPayload::validateRequestsFinished($this->requestsFinished)
        || AuditCompletedPayload::validateRequestsFinishedPerMinute($this->requestsFinishedPerMinute)
        || AuditCompletedPayload::validateRequestsRetries($this->requestsRetries)
        || AuditCompletedPayload::validateRequestsWithStatusCode($this->requestsWithStatusCode)
        || AuditCompletedPayload::validateRequestTotalFailedDurationMillis($this->requestTotalFailedDurationMillis)
        || AuditCompletedPayload::validateRequestTotalFinishedDurationMillis($this->requestTotalFinishedDurationMillis)
        || AuditCompletedPayload::validateRetryErrors($this->retryErrors)
        || AuditCompletedPayload::validateStatsPersistedAt($this->statsPersistedAt);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'auditId'} = $this->toAuditId();
        $out->{'crawlerFinishedAt'} = $this->toCrawlerFinishedAt();
        $out->{'crawlerRuntimeMillis'} = $this->toCrawlerRuntimeMillis();
        $out->{'crawlerStartedAt'} = $this->toCrawlerStartedAt();
        $out->{'errors'} = $this->toErrors();
        $out->{'requestMaxDurationMillis'} = $this->toRequestMaxDurationMillis();
        $out->{'requestMinDurationMillis'} = $this->toRequestMinDurationMillis();
        $out->{'requestsFailed'} = $this->toRequestsFailed();
        $out->{'requestsFailedPerMinute'} = $this->toRequestsFailedPerMinute();
        $out->{'requestsFinished'} = $this->toRequestsFinished();
        $out->{'requestsFinishedPerMinute'} = $this->toRequestsFinishedPerMinute();
        $out->{'requestsRetries'} = $this->toRequestsRetries();
        $out->{'requestsWithStatusCode'} = $this->toRequestsWithStatusCode();
        $out->{'requestTotalFailedDurationMillis'} = $this->toRequestTotalFailedDurationMillis();
        $out->{'requestTotalFinishedDurationMillis'} = $this->toRequestTotalFinishedDurationMillis();
        $out->{'retryErrors'} = $this->toRetryErrors();
        $out->{'statsPersistedAt'} = $this->toStatsPersistedAt();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditCompletedPayload
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditCompletedPayload {
        return new AuditCompletedPayload(
         AuditCompletedPayload::fromAuditId($obj->{'auditId'})
        ,AuditCompletedPayload::fromCrawlerFinishedAt($obj->{'crawlerFinishedAt'})
        ,AuditCompletedPayload::fromCrawlerRuntimeMillis($obj->{'crawlerRuntimeMillis'})
        ,AuditCompletedPayload::fromCrawlerStartedAt($obj->{'crawlerStartedAt'})
        ,AuditCompletedPayload::fromErrors($obj->{'errors'})
        ,AuditCompletedPayload::fromRequestMaxDurationMillis($obj->{'requestMaxDurationMillis'})
        ,AuditCompletedPayload::fromRequestMinDurationMillis($obj->{'requestMinDurationMillis'})
        ,AuditCompletedPayload::fromRequestsFailed($obj->{'requestsFailed'})
        ,AuditCompletedPayload::fromRequestsFailedPerMinute($obj->{'requestsFailedPerMinute'})
        ,AuditCompletedPayload::fromRequestsFinished($obj->{'requestsFinished'})
        ,AuditCompletedPayload::fromRequestsFinishedPerMinute($obj->{'requestsFinishedPerMinute'})
        ,AuditCompletedPayload::fromRequestsRetries($obj->{'requestsRetries'})
        ,AuditCompletedPayload::fromRequestsWithStatusCode($obj->{'requestsWithStatusCode'})
        ,AuditCompletedPayload::fromRequestTotalFailedDurationMillis($obj->{'requestTotalFailedDurationMillis'})
        ,AuditCompletedPayload::fromRequestTotalFinishedDurationMillis($obj->{'requestTotalFinishedDurationMillis'})
        ,AuditCompletedPayload::fromRetryErrors($obj->{'retryErrors'})
        ,AuditCompletedPayload::fromStatsPersistedAt($obj->{'statsPersistedAt'})
        );
    }

    /**
     * @return AuditCompletedPayload
     */
    public static function sample(): AuditCompletedPayload {
        return new AuditCompletedPayload(
         AuditCompletedPayload::sampleAuditId()
        ,AuditCompletedPayload::sampleCrawlerFinishedAt()
        ,AuditCompletedPayload::sampleCrawlerRuntimeMillis()
        ,AuditCompletedPayload::sampleCrawlerStartedAt()
        ,AuditCompletedPayload::sampleErrors()
        ,AuditCompletedPayload::sampleRequestMaxDurationMillis()
        ,AuditCompletedPayload::sampleRequestMinDurationMillis()
        ,AuditCompletedPayload::sampleRequestsFailed()
        ,AuditCompletedPayload::sampleRequestsFailedPerMinute()
        ,AuditCompletedPayload::sampleRequestsFinished()
        ,AuditCompletedPayload::sampleRequestsFinishedPerMinute()
        ,AuditCompletedPayload::sampleRequestsRetries()
        ,AuditCompletedPayload::sampleRequestsWithStatusCode()
        ,AuditCompletedPayload::sampleRequestTotalFailedDurationMillis()
        ,AuditCompletedPayload::sampleRequestTotalFinishedDurationMillis()
        ,AuditCompletedPayload::sampleRetryErrors()
        ,AuditCompletedPayload::sampleStatsPersistedAt()
        );
    }
}

// This is an autogenerated file:AuditCompletedType

class AuditCompletedType {
    public static AuditCompletedType $AUDIT_COMPLETED;
    public static function init() {
        AuditCompletedType::$AUDIT_COMPLETED = new AuditCompletedType('audit.completed');
    }
    private string $enum;
    public function __construct(string $enum) {
        $this->enum = $enum;
    }

    /**
     * @param AuditCompletedType
     * @return string
     * @throws Exception
     */
    public static function to(AuditCompletedType $obj): string {
        switch ($obj->enum) {
            case AuditCompletedType::$AUDIT_COMPLETED->enum: return 'audit.completed';
        }
        throw new Exception('the give value is not an enum-value.');
    }

    /**
     * @param mixed
     * @return AuditCompletedType
     * @throws Exception
     */
    public static function from($obj): AuditCompletedType {
        switch ($obj) {
            case 'audit.completed': return AuditCompletedType::$AUDIT_COMPLETED;
        }
        throw new Exception("Cannot deserialize AuditCompletedType");
    }

    /**
     * @return AuditCompletedType
     */
    public static function sample(): AuditCompletedType {
        return AuditCompletedType::$AUDIT_COMPLETED;
    }
}
AuditCompletedType::init();
