<?php

namespace EqualSite\Events\Value;

use Exception;
use stdClass;

// This is an autogenerated file:AuditFailed

class AuditFailed {
    private AuditFailedPayload $payload; // json:payload Required
    private int $timestamp; // json:timestamp Required
    private AuditFailedType $type; // json:type Required
    private string $version; // json:version Required

    /**
     * @param AuditFailedPayload $payload
     * @param int $timestamp
     * @param AuditFailedType $type
     * @param string $version
     */
    public function __construct(AuditFailedPayload $payload, int $timestamp, AuditFailedType $type, string $version) {
        $this->payload = $payload;
        $this->timestamp = $timestamp;
        $this->type = $type;
        $this->version = $version;
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return AuditFailedPayload
     */
    public static function fromPayload(stdClass $value): AuditFailedPayload {
        return AuditFailedPayload::from($value); /*class*/
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toPayload(): stdClass {
        if (AuditFailed::validatePayload($this->payload))  {
            return $this->payload->to(); /*class*/
        }
        throw new Exception('never get to this AuditFailed::payload');
    }

    /**
     * @param AuditFailedPayload
     * @return bool
     * @throws Exception
     */
    public static function validatePayload(AuditFailedPayload $value): bool {
        $value->validate();
        return true;
    }

    /**
     * @throws Exception
     * @return AuditFailedPayload
     */
    public function getPayload(): AuditFailedPayload {
        if (AuditFailed::validatePayload($this->payload))  {
            return $this->payload;
        }
        throw new Exception('never get to getPayload AuditFailed::payload');
    }

    /**
     * @return AuditFailedPayload
     */
    public static function samplePayload(): AuditFailedPayload {
        return AuditFailedPayload::sample(); /*31:payload*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromTimestamp(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toTimestamp(): int {
        if (AuditFailed::validateTimestamp($this->timestamp))  {
            return $this->timestamp; /*int*/
        }
        throw new Exception('never get to this AuditFailed::timestamp');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateTimestamp(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditFailed::timestamp");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getTimestamp(): int {
        if (AuditFailed::validateTimestamp($this->timestamp))  {
            return $this->timestamp;
        }
        throw new Exception('never get to getTimestamp AuditFailed::timestamp');
    }

    /**
     * @return int
     */
    public static function sampleTimestamp(): int {
        return 32; /*32:timestamp*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return AuditFailedType
     */
    public static function fromType(string $value): AuditFailedType {
        return AuditFailedType::from($value); /*enum*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toType(): string {
        if (AuditFailed::validateType($this->type))  {
            return AuditFailedType::to($this->type); /*enum*/
        }
        throw new Exception('never get to this AuditFailed::type');
    }

    /**
     * @param AuditFailedType
     * @return bool
     * @throws Exception
     */
    public static function validateType(AuditFailedType $value): bool {
        AuditFailedType::to($value);
        return true;
    }

    /**
     * @throws Exception
     * @return AuditFailedType
     */
    public function getType(): AuditFailedType {
        if (AuditFailed::validateType($this->type))  {
            return $this->type;
        }
        throw new Exception('never get to getType AuditFailed::type');
    }

    /**
     * @return AuditFailedType
     */
    public static function sampleType(): AuditFailedType {
        return AuditFailedType::sample(); /*enum*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromVersion(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toVersion(): string {
        if (AuditFailed::validateVersion($this->version))  {
            return $this->version; /*string*/
        }
        throw new Exception('never get to this AuditFailed::version');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateVersion(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditFailed::version");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getVersion(): string {
        if (AuditFailed::validateVersion($this->version))  {
            return $this->version;
        }
        throw new Exception('never get to getVersion AuditFailed::version');
    }

    /**
     * @return string
     */
    public static function sampleVersion(): string {
        return 'AuditFailed::version::34'; /*34:version*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditFailed::validatePayload($this->payload)
        || AuditFailed::validateTimestamp($this->timestamp)
        || AuditFailed::validateType($this->type)
        || AuditFailed::validateVersion($this->version);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'payload'} = $this->toPayload();
        $out->{'timestamp'} = $this->toTimestamp();
        $out->{'type'} = $this->toType();
        $out->{'version'} = $this->toVersion();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditFailed
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditFailed {
        return new AuditFailed(
         AuditFailed::fromPayload($obj->{'payload'})
        ,AuditFailed::fromTimestamp($obj->{'timestamp'})
        ,AuditFailed::fromType($obj->{'type'})
        ,AuditFailed::fromVersion($obj->{'version'})
        );
    }

    /**
     * @return AuditFailed
     */
    public static function sample(): AuditFailed {
        return new AuditFailed(
         AuditFailed::samplePayload()
        ,AuditFailed::sampleTimestamp()
        ,AuditFailed::sampleType()
        ,AuditFailed::sampleVersion()
        );
    }
}

// This is an autogenerated file:AuditFailedPayload

class AuditFailedPayload {
    private string $auditId; // json:auditId Required
    private string $error; // json:error Required

    /**
     * @param string $auditId
     * @param string $error
     */
    public function __construct(string $auditId, string $error) {
        $this->auditId = $auditId;
        $this->error = $error;
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromAuditId(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toAuditId(): string {
        if (AuditFailedPayload::validateAuditId($this->auditId))  {
            return $this->auditId; /*string*/
        }
        throw new Exception('never get to this AuditFailedPayload::auditId');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateAuditId(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditFailedPayload::auditId");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getAuditId(): string {
        if (AuditFailedPayload::validateAuditId($this->auditId))  {
            return $this->auditId;
        }
        throw new Exception('never get to getAuditId AuditFailedPayload::auditId');
    }

    /**
     * @return string
     */
    public static function sampleAuditId(): string {
        return 'AuditFailedPayload::auditId::31'; /*31:auditId*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromError(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toError(): string {
        if (AuditFailedPayload::validateError($this->error))  {
            return $this->error; /*string*/
        }
        throw new Exception('never get to this AuditFailedPayload::error');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateError(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditFailedPayload::error");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getError(): string {
        if (AuditFailedPayload::validateError($this->error))  {
            return $this->error;
        }
        throw new Exception('never get to getError AuditFailedPayload::error');
    }

    /**
     * @return string
     */
    public static function sampleError(): string {
        return 'AuditFailedPayload::error::32'; /*32:error*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditFailedPayload::validateAuditId($this->auditId)
        || AuditFailedPayload::validateError($this->error);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'auditId'} = $this->toAuditId();
        $out->{'error'} = $this->toError();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditFailedPayload
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditFailedPayload {
        return new AuditFailedPayload(
         AuditFailedPayload::fromAuditId($obj->{'auditId'})
        ,AuditFailedPayload::fromError($obj->{'error'})
        );
    }

    /**
     * @return AuditFailedPayload
     */
    public static function sample(): AuditFailedPayload {
        return new AuditFailedPayload(
         AuditFailedPayload::sampleAuditId()
        ,AuditFailedPayload::sampleError()
        );
    }
}

// This is an autogenerated file:AuditFailedType

class AuditFailedType {
    public static AuditFailedType $AUDIT_FAILED;
    public static function init() {
        AuditFailedType::$AUDIT_FAILED = new AuditFailedType('audit.failed');
    }
    private string $enum;
    public function __construct(string $enum) {
        $this->enum = $enum;
    }

    /**
     * @param AuditFailedType
     * @return string
     * @throws Exception
     */
    public static function to(AuditFailedType $obj): string {
        switch ($obj->enum) {
            case AuditFailedType::$AUDIT_FAILED->enum: return 'audit.failed';
        }
        throw new Exception('the give value is not an enum-value.');
    }

    /**
     * @param mixed
     * @return AuditFailedType
     * @throws Exception
     */
    public static function from($obj): AuditFailedType {
        switch ($obj) {
            case 'audit.failed': return AuditFailedType::$AUDIT_FAILED;
        }
        throw new Exception("Cannot deserialize AuditFailedType");
    }

    /**
     * @return AuditFailedType
     */
    public static function sample(): AuditFailedType {
        return AuditFailedType::$AUDIT_FAILED;
    }
}
AuditFailedType::init();
