<?php

namespace EqualSite\Events\Value;

use Exception;
use stdClass;

// This is an autogenerated file:AuditProgress

class AuditProgress {
    private AuditProgressPayload $payload; // json:payload Required
    private int $timestamp; // json:timestamp Required
    private AuditProgressType $type; // json:type Required
    private string $version; // json:version Required

    /**
     * @param AuditProgressPayload $payload
     * @param int $timestamp
     * @param AuditProgressType $type
     * @param string $version
     */
    public function __construct(AuditProgressPayload $payload, int $timestamp, AuditProgressType $type, string $version) {
        $this->payload = $payload;
        $this->timestamp = $timestamp;
        $this->type = $type;
        $this->version = $version;
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return AuditProgressPayload
     */
    public static function fromPayload(stdClass $value): AuditProgressPayload {
        return AuditProgressPayload::from($value); /*class*/
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toPayload(): stdClass {
        if (AuditProgress::validatePayload($this->payload))  {
            return $this->payload->to(); /*class*/
        }
        throw new Exception('never get to this AuditProgress::payload');
    }

    /**
     * @param AuditProgressPayload
     * @return bool
     * @throws Exception
     */
    public static function validatePayload(AuditProgressPayload $value): bool {
        $value->validate();
        return true;
    }

    /**
     * @throws Exception
     * @return AuditProgressPayload
     */
    public function getPayload(): AuditProgressPayload {
        if (AuditProgress::validatePayload($this->payload))  {
            return $this->payload;
        }
        throw new Exception('never get to getPayload AuditProgress::payload');
    }

    /**
     * @return AuditProgressPayload
     */
    public static function samplePayload(): AuditProgressPayload {
        return AuditProgressPayload::sample(); /*31:payload*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromTimestamp(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toTimestamp(): int {
        if (AuditProgress::validateTimestamp($this->timestamp))  {
            return $this->timestamp; /*int*/
        }
        throw new Exception('never get to this AuditProgress::timestamp');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateTimestamp(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditProgress::timestamp");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getTimestamp(): int {
        if (AuditProgress::validateTimestamp($this->timestamp))  {
            return $this->timestamp;
        }
        throw new Exception('never get to getTimestamp AuditProgress::timestamp');
    }

    /**
     * @return int
     */
    public static function sampleTimestamp(): int {
        return 32; /*32:timestamp*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return AuditProgressType
     */
    public static function fromType(string $value): AuditProgressType {
        return AuditProgressType::from($value); /*enum*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toType(): string {
        if (AuditProgress::validateType($this->type))  {
            return AuditProgressType::to($this->type); /*enum*/
        }
        throw new Exception('never get to this AuditProgress::type');
    }

    /**
     * @param AuditProgressType
     * @return bool
     * @throws Exception
     */
    public static function validateType(AuditProgressType $value): bool {
        AuditProgressType::to($value);
        return true;
    }

    /**
     * @throws Exception
     * @return AuditProgressType
     */
    public function getType(): AuditProgressType {
        if (AuditProgress::validateType($this->type))  {
            return $this->type;
        }
        throw new Exception('never get to getType AuditProgress::type');
    }

    /**
     * @return AuditProgressType
     */
    public static function sampleType(): AuditProgressType {
        return AuditProgressType::sample(); /*enum*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromVersion(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toVersion(): string {
        if (AuditProgress::validateVersion($this->version))  {
            return $this->version; /*string*/
        }
        throw new Exception('never get to this AuditProgress::version');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateVersion(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditProgress::version");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getVersion(): string {
        if (AuditProgress::validateVersion($this->version))  {
            return $this->version;
        }
        throw new Exception('never get to getVersion AuditProgress::version');
    }

    /**
     * @return string
     */
    public static function sampleVersion(): string {
        return 'AuditProgress::version::34'; /*34:version*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditProgress::validatePayload($this->payload)
        || AuditProgress::validateTimestamp($this->timestamp)
        || AuditProgress::validateType($this->type)
        || AuditProgress::validateVersion($this->version);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'payload'} = $this->toPayload();
        $out->{'timestamp'} = $this->toTimestamp();
        $out->{'type'} = $this->toType();
        $out->{'version'} = $this->toVersion();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditProgress
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditProgress {
        return new AuditProgress(
         AuditProgress::fromPayload($obj->{'payload'})
        ,AuditProgress::fromTimestamp($obj->{'timestamp'})
        ,AuditProgress::fromType($obj->{'type'})
        ,AuditProgress::fromVersion($obj->{'version'})
        );
    }

    /**
     * @return AuditProgress
     */
    public static function sample(): AuditProgress {
        return new AuditProgress(
         AuditProgress::samplePayload()
        ,AuditProgress::sampleTimestamp()
        ,AuditProgress::sampleType()
        ,AuditProgress::sampleVersion()
        );
    }
}

// This is an autogenerated file:AuditProgressPayload

class AuditProgressPayload {
    private string $auditId; // json:auditId Required
    private int $completedRequests; // json:completedRequests Required
    private int $pendingRequests; // json:pendingRequests Required
    private float $progressPercentage; // json:progressPercentage Required
    private int $totalRequests; // json:totalRequests Required

    /**
     * @param string $auditId
     * @param int $completedRequests
     * @param int $pendingRequests
     * @param float $progressPercentage
     * @param int $totalRequests
     */
    public function __construct(string $auditId, int $completedRequests, int $pendingRequests, float $progressPercentage, int $totalRequests) {
        $this->auditId = $auditId;
        $this->completedRequests = $completedRequests;
        $this->pendingRequests = $pendingRequests;
        $this->progressPercentage = $progressPercentage;
        $this->totalRequests = $totalRequests;
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromAuditId(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toAuditId(): string {
        if (AuditProgressPayload::validateAuditId($this->auditId))  {
            return $this->auditId; /*string*/
        }
        throw new Exception('never get to this AuditProgressPayload::auditId');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateAuditId(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditProgressPayload::auditId");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getAuditId(): string {
        if (AuditProgressPayload::validateAuditId($this->auditId))  {
            return $this->auditId;
        }
        throw new Exception('never get to getAuditId AuditProgressPayload::auditId');
    }

    /**
     * @return string
     */
    public static function sampleAuditId(): string {
        return 'AuditProgressPayload::auditId::31'; /*31:auditId*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromCompletedRequests(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toCompletedRequests(): int {
        if (AuditProgressPayload::validateCompletedRequests($this->completedRequests))  {
            return $this->completedRequests; /*int*/
        }
        throw new Exception('never get to this AuditProgressPayload::completedRequests');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateCompletedRequests(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditProgressPayload::completedRequests");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getCompletedRequests(): int {
        if (AuditProgressPayload::validateCompletedRequests($this->completedRequests))  {
            return $this->completedRequests;
        }
        throw new Exception('never get to getCompletedRequests AuditProgressPayload::completedRequests');
    }

    /**
     * @return int
     */
    public static function sampleCompletedRequests(): int {
        return 32; /*32:completedRequests*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromPendingRequests(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toPendingRequests(): int {
        if (AuditProgressPayload::validatePendingRequests($this->pendingRequests))  {
            return $this->pendingRequests; /*int*/
        }
        throw new Exception('never get to this AuditProgressPayload::pendingRequests');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validatePendingRequests(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditProgressPayload::pendingRequests");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getPendingRequests(): int {
        if (AuditProgressPayload::validatePendingRequests($this->pendingRequests))  {
            return $this->pendingRequests;
        }
        throw new Exception('never get to getPendingRequests AuditProgressPayload::pendingRequests');
    }

    /**
     * @return int
     */
    public static function samplePendingRequests(): int {
        return 33; /*33:pendingRequests*/
    }

    /**
     * @param float $value
     * @throws Exception
     * @return float
     */
    public static function fromProgressPercentage(float $value): float {
        return $value; /*float*/
    }

    /**
     * @throws Exception
     * @return float
     */
    public function toProgressPercentage(): float {
        if (AuditProgressPayload::validateProgressPercentage($this->progressPercentage))  {
            return $this->progressPercentage; /*float*/
        }
        throw new Exception('never get to this AuditProgressPayload::progressPercentage');
    }

    /**
     * @param float
     * @return bool
     * @throws Exception
     */
    public static function validateProgressPercentage(float $value): bool {
        if (!is_float($value) && !is_int($value)) {
            throw new Exception("Attribute Error:AuditProgressPayload::progressPercentage");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return float
     */
    public function getProgressPercentage(): float {
        if (AuditProgressPayload::validateProgressPercentage($this->progressPercentage))  {
            return $this->progressPercentage;
        }
        throw new Exception('never get to getProgressPercentage AuditProgressPayload::progressPercentage');
    }

    /**
     * @return float
     */
    public static function sampleProgressPercentage(): float {
        return 34.034; /*34:progressPercentage*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromTotalRequests(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toTotalRequests(): int {
        if (AuditProgressPayload::validateTotalRequests($this->totalRequests))  {
            return $this->totalRequests; /*int*/
        }
        throw new Exception('never get to this AuditProgressPayload::totalRequests');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateTotalRequests(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditProgressPayload::totalRequests");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getTotalRequests(): int {
        if (AuditProgressPayload::validateTotalRequests($this->totalRequests))  {
            return $this->totalRequests;
        }
        throw new Exception('never get to getTotalRequests AuditProgressPayload::totalRequests');
    }

    /**
     * @return int
     */
    public static function sampleTotalRequests(): int {
        return 35; /*35:totalRequests*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditProgressPayload::validateAuditId($this->auditId)
        || AuditProgressPayload::validateCompletedRequests($this->completedRequests)
        || AuditProgressPayload::validatePendingRequests($this->pendingRequests)
        || AuditProgressPayload::validateProgressPercentage($this->progressPercentage)
        || AuditProgressPayload::validateTotalRequests($this->totalRequests);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'auditId'} = $this->toAuditId();
        $out->{'completedRequests'} = $this->toCompletedRequests();
        $out->{'pendingRequests'} = $this->toPendingRequests();
        $out->{'progressPercentage'} = $this->toProgressPercentage();
        $out->{'totalRequests'} = $this->toTotalRequests();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditProgressPayload
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditProgressPayload {
        return new AuditProgressPayload(
         AuditProgressPayload::fromAuditId($obj->{'auditId'})
        ,AuditProgressPayload::fromCompletedRequests($obj->{'completedRequests'})
        ,AuditProgressPayload::fromPendingRequests($obj->{'pendingRequests'})
        ,AuditProgressPayload::fromProgressPercentage($obj->{'progressPercentage'})
        ,AuditProgressPayload::fromTotalRequests($obj->{'totalRequests'})
        );
    }

    /**
     * @return AuditProgressPayload
     */
    public static function sample(): AuditProgressPayload {
        return new AuditProgressPayload(
         AuditProgressPayload::sampleAuditId()
        ,AuditProgressPayload::sampleCompletedRequests()
        ,AuditProgressPayload::samplePendingRequests()
        ,AuditProgressPayload::sampleProgressPercentage()
        ,AuditProgressPayload::sampleTotalRequests()
        );
    }
}

// This is an autogenerated file:AuditProgressType

class AuditProgressType {
    public static AuditProgressType $AUDIT_PROGRESS;
    public static function init() {
        AuditProgressType::$AUDIT_PROGRESS = new AuditProgressType('audit.progress');
    }
    private string $enum;
    public function __construct(string $enum) {
        $this->enum = $enum;
    }

    /**
     * @param AuditProgressType
     * @return string
     * @throws Exception
     */
    public static function to(AuditProgressType $obj): string {
        switch ($obj->enum) {
            case AuditProgressType::$AUDIT_PROGRESS->enum: return 'audit.progress';
        }
        throw new Exception('the give value is not an enum-value.');
    }

    /**
     * @param mixed
     * @return AuditProgressType
     * @throws Exception
     */
    public static function from($obj): AuditProgressType {
        switch ($obj) {
            case 'audit.progress': return AuditProgressType::$AUDIT_PROGRESS;
        }
        throw new Exception("Cannot deserialize AuditProgressType");
    }

    /**
     * @return AuditProgressType
     */
    public static function sample(): AuditProgressType {
        return AuditProgressType::$AUDIT_PROGRESS;
    }
}
AuditProgressType::init();
