<?php

namespace EqualSite\Events\Value;

use Exception;
use stdClass;

// This is an autogenerated file:AuditCancelled

class AuditCancelled {
    private AuditCancelledPayload $payload; // json:payload Required
    private int $timestamp; // json:timestamp Required
    private AuditCancelledType $type; // json:type Required
    private string $version; // json:version Required

    /**
     * @param AuditCancelledPayload $payload
     * @param int $timestamp
     * @param AuditCancelledType $type
     * @param string $version
     */
    public function __construct(AuditCancelledPayload $payload, int $timestamp, AuditCancelledType $type, string $version) {
        $this->payload = $payload;
        $this->timestamp = $timestamp;
        $this->type = $type;
        $this->version = $version;
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return AuditCancelledPayload
     */
    public static function fromPayload(stdClass $value): AuditCancelledPayload {
        return AuditCancelledPayload::from($value); /*class*/
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toPayload(): stdClass {
        if (AuditCancelled::validatePayload($this->payload))  {
            return $this->payload->to(); /*class*/
        }
        throw new Exception('never get to this AuditCancelled::payload');
    }

    /**
     * @param AuditCancelledPayload
     * @return bool
     * @throws Exception
     */
    public static function validatePayload(AuditCancelledPayload $value): bool {
        $value->validate();
        return true;
    }

    /**
     * @throws Exception
     * @return AuditCancelledPayload
     */
    public function getPayload(): AuditCancelledPayload {
        if (AuditCancelled::validatePayload($this->payload))  {
            return $this->payload;
        }
        throw new Exception('never get to getPayload AuditCancelled::payload');
    }

    /**
     * @return AuditCancelledPayload
     */
    public static function samplePayload(): AuditCancelledPayload {
        return AuditCancelledPayload::sample(); /*31:payload*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromTimestamp(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toTimestamp(): int {
        if (AuditCancelled::validateTimestamp($this->timestamp))  {
            return $this->timestamp; /*int*/
        }
        throw new Exception('never get to this AuditCancelled::timestamp');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateTimestamp(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditCancelled::timestamp");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getTimestamp(): int {
        if (AuditCancelled::validateTimestamp($this->timestamp))  {
            return $this->timestamp;
        }
        throw new Exception('never get to getTimestamp AuditCancelled::timestamp');
    }

    /**
     * @return int
     */
    public static function sampleTimestamp(): int {
        return 32; /*32:timestamp*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return AuditCancelledType
     */
    public static function fromType(string $value): AuditCancelledType {
        return AuditCancelledType::from($value); /*enum*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toType(): string {
        if (AuditCancelled::validateType($this->type))  {
            return AuditCancelledType::to($this->type); /*enum*/
        }
        throw new Exception('never get to this AuditCancelled::type');
    }

    /**
     * @param AuditCancelledType
     * @return bool
     * @throws Exception
     */
    public static function validateType(AuditCancelledType $value): bool {
        AuditCancelledType::to($value);
        return true;
    }

    /**
     * @throws Exception
     * @return AuditCancelledType
     */
    public function getType(): AuditCancelledType {
        if (AuditCancelled::validateType($this->type))  {
            return $this->type;
        }
        throw new Exception('never get to getType AuditCancelled::type');
    }

    /**
     * @return AuditCancelledType
     */
    public static function sampleType(): AuditCancelledType {
        return AuditCancelledType::sample(); /*enum*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromVersion(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toVersion(): string {
        if (AuditCancelled::validateVersion($this->version))  {
            return $this->version; /*string*/
        }
        throw new Exception('never get to this AuditCancelled::version');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateVersion(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditCancelled::version");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getVersion(): string {
        if (AuditCancelled::validateVersion($this->version))  {
            return $this->version;
        }
        throw new Exception('never get to getVersion AuditCancelled::version');
    }

    /**
     * @return string
     */
    public static function sampleVersion(): string {
        return 'AuditCancelled::version::34'; /*34:version*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditCancelled::validatePayload($this->payload)
        || AuditCancelled::validateTimestamp($this->timestamp)
        || AuditCancelled::validateType($this->type)
        || AuditCancelled::validateVersion($this->version);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'payload'} = $this->toPayload();
        $out->{'timestamp'} = $this->toTimestamp();
        $out->{'type'} = $this->toType();
        $out->{'version'} = $this->toVersion();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditCancelled
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditCancelled {
        return new AuditCancelled(
         AuditCancelled::fromPayload($obj->{'payload'})
        ,AuditCancelled::fromTimestamp($obj->{'timestamp'})
        ,AuditCancelled::fromType($obj->{'type'})
        ,AuditCancelled::fromVersion($obj->{'version'})
        );
    }

    /**
     * @return AuditCancelled
     */
    public static function sample(): AuditCancelled {
        return new AuditCancelled(
         AuditCancelled::samplePayload()
        ,AuditCancelled::sampleTimestamp()
        ,AuditCancelled::sampleType()
        ,AuditCancelled::sampleVersion()
        );
    }
}

// This is an autogenerated file:AuditCancelledPayload

class AuditCancelledPayload {
    private string $auditId; // json:auditId Required
    private ?string $crawlerFinishedAt; // json:crawlerFinishedAt Optional
    private float $crawlerRuntimeMillis; // json:crawlerRuntimeMillis Required
    private ?string $crawlerStartedAt; // json:crawlerStartedAt Optional
    private stdClass $errors; // json:errors Required
    private float $requestMaxDurationMillis; // json:requestMaxDurationMillis Required
    private float $requestMinDurationMillis; // json:requestMinDurationMillis Required
    private int $requestsFailed; // json:requestsFailed Required
    private float $requestsFailedPerMinute; // json:requestsFailedPerMinute Required
    private int $requestsFinished; // json:requestsFinished Required
    private float $requestsFinishedPerMinute; // json:requestsFinishedPerMinute Required
    private int $requestsRetries; // json:requestsRetries Required
    private stdClass $requestsWithStatusCode; // json:requestsWithStatusCode Required
    private float $requestTotalFailedDurationMillis; // json:requestTotalFailedDurationMillis Required
    private float $requestTotalFinishedDurationMillis; // json:requestTotalFinishedDurationMillis Required
    private stdClass $retryErrors; // json:retryErrors Required
    private ?string $statsPersistedAt; // json:statsPersistedAt Optional

    /**
     * @param string $auditId
     * @param string|null $crawlerFinishedAt
     * @param float $crawlerRuntimeMillis
     * @param string|null $crawlerStartedAt
     * @param stdClass $errors
     * @param float $requestMaxDurationMillis
     * @param float $requestMinDurationMillis
     * @param int $requestsFailed
     * @param float $requestsFailedPerMinute
     * @param int $requestsFinished
     * @param float $requestsFinishedPerMinute
     * @param int $requestsRetries
     * @param stdClass $requestsWithStatusCode
     * @param float $requestTotalFailedDurationMillis
     * @param float $requestTotalFinishedDurationMillis
     * @param stdClass $retryErrors
     * @param string|null $statsPersistedAt
     */
    public function __construct(string $auditId, ?string $crawlerFinishedAt, float $crawlerRuntimeMillis, ?string $crawlerStartedAt, stdClass $errors, float $requestMaxDurationMillis, float $requestMinDurationMillis, int $requestsFailed, float $requestsFailedPerMinute, int $requestsFinished, float $requestsFinishedPerMinute, int $requestsRetries, stdClass $requestsWithStatusCode, float $requestTotalFailedDurationMillis, float $requestTotalFinishedDurationMillis, stdClass $retryErrors, ?string $statsPersistedAt) {
        $this->auditId = $auditId;
        $this->crawlerFinishedAt = $crawlerFinishedAt;
        $this->crawlerRuntimeMillis = $crawlerRuntimeMillis;
        $this->crawlerStartedAt = $crawlerStartedAt;
        $this->errors = $errors;
        $this->requestMaxDurationMillis = $requestMaxDurationMillis;
        $this->requestMinDurationMillis = $requestMinDurationMillis;
        $this->requestsFailed = $requestsFailed;
        $this->requestsFailedPerMinute = $requestsFailedPerMinute;
        $this->requestsFinished = $requestsFinished;
        $this->requestsFinishedPerMinute = $requestsFinishedPerMinute;
        $this->requestsRetries = $requestsRetries;
        $this->requestsWithStatusCode = $requestsWithStatusCode;
        $this->requestTotalFailedDurationMillis = $requestTotalFailedDurationMillis;
        $this->requestTotalFinishedDurationMillis = $requestTotalFinishedDurationMillis;
        $this->retryErrors = $retryErrors;
        $this->statsPersistedAt = $statsPersistedAt;
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromAuditId(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toAuditId(): string {
        if (AuditCancelledPayload::validateAuditId($this->auditId))  {
            return $this->auditId; /*string*/
        }
        throw new Exception('never get to this AuditCancelledPayload::auditId');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateAuditId(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditCancelledPayload::auditId");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getAuditId(): string {
        if (AuditCancelledPayload::validateAuditId($this->auditId))  {
            return $this->auditId;
        }
        throw new Exception('never get to getAuditId AuditCancelledPayload::auditId');
    }

    /**
     * @return string
     */
    public static function sampleAuditId(): string {
        return 'AuditCancelledPayload::auditId::31'; /*31:auditId*/
    }

    /**
     * @param ?string $value
     * @throws Exception
     * @return ?string
     */
    public static function fromCrawlerFinishedAt(?string $value): ?string {
        if (!is_null($value)) {
            return $value; /*string*/
        } else {
            return  null;
        }
    }

    /**
     * @throws Exception
     * @return ?string
     */
    public function toCrawlerFinishedAt(): ?string {
        if (AuditCancelledPayload::validateCrawlerFinishedAt($this->crawlerFinishedAt))  {
            if (!is_null($this->crawlerFinishedAt)) {
                return $this->crawlerFinishedAt; /*string*/
            } else {
                return  null;
            }
        }
        throw new Exception('never get to this AuditCancelledPayload::crawlerFinishedAt');
    }

    /**
     * @param string|null
     * @return bool
     * @throws Exception
     */
    public static function validateCrawlerFinishedAt(?string $value): bool {
        if (!is_null($value)) {
            if (!is_string($value)) {
                throw new Exception("Attribute Error:AuditCancelledPayload::crawlerFinishedAt");
            }
        }
        return true;
    }

    /**
     * @throws Exception
     * @return ?string
     */
    public function getCrawlerFinishedAt(): ?string {
        if (AuditCancelledPayload::validateCrawlerFinishedAt($this->crawlerFinishedAt))  {
            return $this->crawlerFinishedAt;
        }
        throw new Exception('never get to getCrawlerFinishedAt AuditCancelledPayload::crawlerFinishedAt');
    }

    /**
     * @return ?string
     */
    public static function sampleCrawlerFinishedAt(): ?string {
        return 'AuditCancelledPayload::crawlerFinishedAt::32'; /*32:crawlerFinishedAt*/
    }

    /**
     * @param float $value
     * @throws Exception
     * @return float
     */
    public static function fromCrawlerRuntimeMillis(float $value): float {
        return $value; /*float*/
    }

    /**
     * @throws Exception
     * @return float
     */
    public function toCrawlerRuntimeMillis(): float {
        if (AuditCancelledPayload::validateCrawlerRuntimeMillis($this->crawlerRuntimeMillis))  {
            return $this->crawlerRuntimeMillis; /*float*/
        }
        throw new Exception('never get to this AuditCancelledPayload::crawlerRuntimeMillis');
    }

    /**
     * @param float
     * @return bool
     * @throws Exception
     */
    public static function validateCrawlerRuntimeMillis(float $value): bool {
        if (!is_float($value) && !is_int($value)) {
            throw new Exception("Attribute Error:AuditCancelledPayload::crawlerRuntimeMillis");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return float
     */
    public function getCrawlerRuntimeMillis(): float {
        if (AuditCancelledPayload::validateCrawlerRuntimeMillis($this->crawlerRuntimeMillis))  {
            return $this->crawlerRuntimeMillis;
        }
        throw new Exception('never get to getCrawlerRuntimeMillis AuditCancelledPayload::crawlerRuntimeMillis');
    }

    /**
     * @return float
     */
    public static function sampleCrawlerRuntimeMillis(): float {
        return 33.033; /*33:crawlerRuntimeMillis*/
    }

    /**
     * @param ?string $value
     * @throws Exception
     * @return ?string
     */
    public static function fromCrawlerStartedAt(?string $value): ?string {
        if (!is_null($value)) {
            return $value; /*string*/
        } else {
            return  null;
        }
    }

    /**
     * @throws Exception
     * @return ?string
     */
    public function toCrawlerStartedAt(): ?string {
        if (AuditCancelledPayload::validateCrawlerStartedAt($this->crawlerStartedAt))  {
            if (!is_null($this->crawlerStartedAt)) {
                return $this->crawlerStartedAt; /*string*/
            } else {
                return  null;
            }
        }
        throw new Exception('never get to this AuditCancelledPayload::crawlerStartedAt');
    }

    /**
     * @param string|null
     * @return bool
     * @throws Exception
     */
    public static function validateCrawlerStartedAt(?string $value): bool {
        if (!is_null($value)) {
            if (!is_string($value)) {
                throw new Exception("Attribute Error:AuditCancelledPayload::crawlerStartedAt");
            }
        }
        return true;
    }

    /**
     * @throws Exception
     * @return ?string
     */
    public function getCrawlerStartedAt(): ?string {
        if (AuditCancelledPayload::validateCrawlerStartedAt($this->crawlerStartedAt))  {
            return $this->crawlerStartedAt;
        }
        throw new Exception('never get to getCrawlerStartedAt AuditCancelledPayload::crawlerStartedAt');
    }

    /**
     * @return ?string
     */
    public static function sampleCrawlerStartedAt(): ?string {
        return 'AuditCancelledPayload::crawlerStartedAt::34'; /*34:crawlerStartedAt*/
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return stdClass
     */
    public static function fromErrors(stdClass $value): stdClass {
        $out = new stdClass();
        foreach ($value as $k => $v) {
            $out->$k = $v; /*any*/
        }
        return $out;
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toErrors(): stdClass {
        if (AuditCancelledPayload::validateErrors($this->errors))  {
            $out = new stdClass();
            foreach ($this->errors as $k => $v) {
                $out->$k = $v; /*any*/
            }
            return $out;
        }
        throw new Exception('never get to this AuditCancelledPayload::errors');
    }

    /**
     * @param stdClass
     * @return bool
     * @throws Exception
     */
    public static function validateErrors(stdClass $value): bool {
        foreach ($value as $k => $v) {
        }
        return true;
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function getErrors(): stdClass {
        if (AuditCancelledPayload::validateErrors($this->errors))  {
            return $this->errors;
        }
        throw new Exception('never get to getErrors AuditCancelledPayload::errors');
    }

    /**
     * @return stdClass
     */
    public static function sampleErrors(): stdClass {
        return  (function () {
            $out = new stdClass();
            $out->{'AuditCancelledPayload'} = 'AnyType::AuditCancelledPayload::errors::35';/*35:errors*/
            return $out;
        })(); /* 35:errors*/
    }

    /**
     * @param float $value
     * @throws Exception
     * @return float
     */
    public static function fromRequestMaxDurationMillis(float $value): float {
        return $value; /*float*/
    }

    /**
     * @throws Exception
     * @return float
     */
    public function toRequestMaxDurationMillis(): float {
        if (AuditCancelledPayload::validateRequestMaxDurationMillis($this->requestMaxDurationMillis))  {
            return $this->requestMaxDurationMillis; /*float*/
        }
        throw new Exception('never get to this AuditCancelledPayload::requestMaxDurationMillis');
    }

    /**
     * @param float
     * @return bool
     * @throws Exception
     */
    public static function validateRequestMaxDurationMillis(float $value): bool {
        if (!is_float($value) && !is_int($value)) {
            throw new Exception("Attribute Error:AuditCancelledPayload::requestMaxDurationMillis");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return float
     */
    public function getRequestMaxDurationMillis(): float {
        if (AuditCancelledPayload::validateRequestMaxDurationMillis($this->requestMaxDurationMillis))  {
            return $this->requestMaxDurationMillis;
        }
        throw new Exception('never get to getRequestMaxDurationMillis AuditCancelledPayload::requestMaxDurationMillis');
    }

    /**
     * @return float
     */
    public static function sampleRequestMaxDurationMillis(): float {
        return 36.036; /*36:requestMaxDurationMillis*/
    }

    /**
     * @param float $value
     * @throws Exception
     * @return float
     */
    public static function fromRequestMinDurationMillis(float $value): float {
        return $value; /*float*/
    }

    /**
     * @throws Exception
     * @return float
     */
    public function toRequestMinDurationMillis(): float {
        if (AuditCancelledPayload::validateRequestMinDurationMillis($this->requestMinDurationMillis))  {
            return $this->requestMinDurationMillis; /*float*/
        }
        throw new Exception('never get to this AuditCancelledPayload::requestMinDurationMillis');
    }

    /**
     * @param float
     * @return bool
     * @throws Exception
     */
    public static function validateRequestMinDurationMillis(float $value): bool {
        if (!is_float($value) && !is_int($value)) {
            throw new Exception("Attribute Error:AuditCancelledPayload::requestMinDurationMillis");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return float
     */
    public function getRequestMinDurationMillis(): float {
        if (AuditCancelledPayload::validateRequestMinDurationMillis($this->requestMinDurationMillis))  {
            return $this->requestMinDurationMillis;
        }
        throw new Exception('never get to getRequestMinDurationMillis AuditCancelledPayload::requestMinDurationMillis');
    }

    /**
     * @return float
     */
    public static function sampleRequestMinDurationMillis(): float {
        return 37.037; /*37:requestMinDurationMillis*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromRequestsFailed(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toRequestsFailed(): int {
        if (AuditCancelledPayload::validateRequestsFailed($this->requestsFailed))  {
            return $this->requestsFailed; /*int*/
        }
        throw new Exception('never get to this AuditCancelledPayload::requestsFailed');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateRequestsFailed(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditCancelledPayload::requestsFailed");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getRequestsFailed(): int {
        if (AuditCancelledPayload::validateRequestsFailed($this->requestsFailed))  {
            return $this->requestsFailed;
        }
        throw new Exception('never get to getRequestsFailed AuditCancelledPayload::requestsFailed');
    }

    /**
     * @return int
     */
    public static function sampleRequestsFailed(): int {
        return 38; /*38:requestsFailed*/
    }

    /**
     * @param float $value
     * @throws Exception
     * @return float
     */
    public static function fromRequestsFailedPerMinute(float $value): float {
        return $value; /*float*/
    }

    /**
     * @throws Exception
     * @return float
     */
    public function toRequestsFailedPerMinute(): float {
        if (AuditCancelledPayload::validateRequestsFailedPerMinute($this->requestsFailedPerMinute))  {
            return $this->requestsFailedPerMinute; /*float*/
        }
        throw new Exception('never get to this AuditCancelledPayload::requestsFailedPerMinute');
    }

    /**
     * @param float
     * @return bool
     * @throws Exception
     */
    public static function validateRequestsFailedPerMinute(float $value): bool {
        if (!is_float($value) && !is_int($value)) {
            throw new Exception("Attribute Error:AuditCancelledPayload::requestsFailedPerMinute");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return float
     */
    public function getRequestsFailedPerMinute(): float {
        if (AuditCancelledPayload::validateRequestsFailedPerMinute($this->requestsFailedPerMinute))  {
            return $this->requestsFailedPerMinute;
        }
        throw new Exception('never get to getRequestsFailedPerMinute AuditCancelledPayload::requestsFailedPerMinute');
    }

    /**
     * @return float
     */
    public static function sampleRequestsFailedPerMinute(): float {
        return 39.039; /*39:requestsFailedPerMinute*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromRequestsFinished(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toRequestsFinished(): int {
        if (AuditCancelledPayload::validateRequestsFinished($this->requestsFinished))  {
            return $this->requestsFinished; /*int*/
        }
        throw new Exception('never get to this AuditCancelledPayload::requestsFinished');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateRequestsFinished(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditCancelledPayload::requestsFinished");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getRequestsFinished(): int {
        if (AuditCancelledPayload::validateRequestsFinished($this->requestsFinished))  {
            return $this->requestsFinished;
        }
        throw new Exception('never get to getRequestsFinished AuditCancelledPayload::requestsFinished');
    }

    /**
     * @return int
     */
    public static function sampleRequestsFinished(): int {
        return 40; /*40:requestsFinished*/
    }

    /**
     * @param float $value
     * @throws Exception
     * @return float
     */
    public static function fromRequestsFinishedPerMinute(float $value): float {
        return $value; /*float*/
    }

    /**
     * @throws Exception
     * @return float
     */
    public function toRequestsFinishedPerMinute(): float {
        if (AuditCancelledPayload::validateRequestsFinishedPerMinute($this->requestsFinishedPerMinute))  {
            return $this->requestsFinishedPerMinute; /*float*/
        }
        throw new Exception('never get to this AuditCancelledPayload::requestsFinishedPerMinute');
    }

    /**
     * @param float
     * @return bool
     * @throws Exception
     */
    public static function validateRequestsFinishedPerMinute(float $value): bool {
        if (!is_float($value) && !is_int($value)) {
            throw new Exception("Attribute Error:AuditCancelledPayload::requestsFinishedPerMinute");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return float
     */
    public function getRequestsFinishedPerMinute(): float {
        if (AuditCancelledPayload::validateRequestsFinishedPerMinute($this->requestsFinishedPerMinute))  {
            return $this->requestsFinishedPerMinute;
        }
        throw new Exception('never get to getRequestsFinishedPerMinute AuditCancelledPayload::requestsFinishedPerMinute');
    }

    /**
     * @return float
     */
    public static function sampleRequestsFinishedPerMinute(): float {
        return 41.041; /*41:requestsFinishedPerMinute*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromRequestsRetries(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toRequestsRetries(): int {
        if (AuditCancelledPayload::validateRequestsRetries($this->requestsRetries))  {
            return $this->requestsRetries; /*int*/
        }
        throw new Exception('never get to this AuditCancelledPayload::requestsRetries');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateRequestsRetries(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditCancelledPayload::requestsRetries");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getRequestsRetries(): int {
        if (AuditCancelledPayload::validateRequestsRetries($this->requestsRetries))  {
            return $this->requestsRetries;
        }
        throw new Exception('never get to getRequestsRetries AuditCancelledPayload::requestsRetries');
    }

    /**
     * @return int
     */
    public static function sampleRequestsRetries(): int {
        return 42; /*42:requestsRetries*/
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return stdClass
     */
    public static function fromRequestsWithStatusCode(stdClass $value): stdClass {
        $out = new stdClass();
        foreach ($value as $k => $v) {
            $out->$k = $v; /*int*/
        }
        return $out;
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toRequestsWithStatusCode(): stdClass {
        if (AuditCancelledPayload::validateRequestsWithStatusCode($this->requestsWithStatusCode))  {
            $out = new stdClass();
            foreach ($this->requestsWithStatusCode as $k => $v) {
                $out->$k = $v; /*int*/
            }
            return $out;
        }
        throw new Exception('never get to this AuditCancelledPayload::requestsWithStatusCode');
    }

    /**
     * @param stdClass
     * @return bool
     * @throws Exception
     */
    public static function validateRequestsWithStatusCode(stdClass $value): bool {
        foreach ($value as $k => $v) {
            if (!is_integer($v)) {
                throw new Exception("Attribute Error:AuditCancelledPayload::requestsWithStatusCode");
            }
        }
        return true;
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function getRequestsWithStatusCode(): stdClass {
        if (AuditCancelledPayload::validateRequestsWithStatusCode($this->requestsWithStatusCode))  {
            return $this->requestsWithStatusCode;
        }
        throw new Exception('never get to getRequestsWithStatusCode AuditCancelledPayload::requestsWithStatusCode');
    }

    /**
     * @return stdClass
     */
    public static function sampleRequestsWithStatusCode(): stdClass {
        return  (function () {
            $out = new stdClass();
            $out->{'AuditCancelledPayload'} = 43; /*43:requestsWithStatusCode*/
            return $out;
        })(); /* 43:requestsWithStatusCode*/
    }

    /**
     * @param float $value
     * @throws Exception
     * @return float
     */
    public static function fromRequestTotalFailedDurationMillis(float $value): float {
        return $value; /*float*/
    }

    /**
     * @throws Exception
     * @return float
     */
    public function toRequestTotalFailedDurationMillis(): float {
        if (AuditCancelledPayload::validateRequestTotalFailedDurationMillis($this->requestTotalFailedDurationMillis))  {
            return $this->requestTotalFailedDurationMillis; /*float*/
        }
        throw new Exception('never get to this AuditCancelledPayload::requestTotalFailedDurationMillis');
    }

    /**
     * @param float
     * @return bool
     * @throws Exception
     */
    public static function validateRequestTotalFailedDurationMillis(float $value): bool {
        if (!is_float($value) && !is_int($value)) {
            throw new Exception("Attribute Error:AuditCancelledPayload::requestTotalFailedDurationMillis");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return float
     */
    public function getRequestTotalFailedDurationMillis(): float {
        if (AuditCancelledPayload::validateRequestTotalFailedDurationMillis($this->requestTotalFailedDurationMillis))  {
            return $this->requestTotalFailedDurationMillis;
        }
        throw new Exception('never get to getRequestTotalFailedDurationMillis AuditCancelledPayload::requestTotalFailedDurationMillis');
    }

    /**
     * @return float
     */
    public static function sampleRequestTotalFailedDurationMillis(): float {
        return 44.044; /*44:requestTotalFailedDurationMillis*/
    }

    /**
     * @param float $value
     * @throws Exception
     * @return float
     */
    public static function fromRequestTotalFinishedDurationMillis(float $value): float {
        return $value; /*float*/
    }

    /**
     * @throws Exception
     * @return float
     */
    public function toRequestTotalFinishedDurationMillis(): float {
        if (AuditCancelledPayload::validateRequestTotalFinishedDurationMillis($this->requestTotalFinishedDurationMillis))  {
            return $this->requestTotalFinishedDurationMillis; /*float*/
        }
        throw new Exception('never get to this AuditCancelledPayload::requestTotalFinishedDurationMillis');
    }

    /**
     * @param float
     * @return bool
     * @throws Exception
     */
    public static function validateRequestTotalFinishedDurationMillis(float $value): bool {
        if (!is_float($value) && !is_int($value)) {
            throw new Exception("Attribute Error:AuditCancelledPayload::requestTotalFinishedDurationMillis");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return float
     */
    public function getRequestTotalFinishedDurationMillis(): float {
        if (AuditCancelledPayload::validateRequestTotalFinishedDurationMillis($this->requestTotalFinishedDurationMillis))  {
            return $this->requestTotalFinishedDurationMillis;
        }
        throw new Exception('never get to getRequestTotalFinishedDurationMillis AuditCancelledPayload::requestTotalFinishedDurationMillis');
    }

    /**
     * @return float
     */
    public static function sampleRequestTotalFinishedDurationMillis(): float {
        return 45.045; /*45:requestTotalFinishedDurationMillis*/
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return stdClass
     */
    public static function fromRetryErrors(stdClass $value): stdClass {
        $out = new stdClass();
        foreach ($value as $k => $v) {
            $out->$k = $v; /*any*/
        }
        return $out;
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toRetryErrors(): stdClass {
        if (AuditCancelledPayload::validateRetryErrors($this->retryErrors))  {
            $out = new stdClass();
            foreach ($this->retryErrors as $k => $v) {
                $out->$k = $v; /*any*/
            }
            return $out;
        }
        throw new Exception('never get to this AuditCancelledPayload::retryErrors');
    }

    /**
     * @param stdClass
     * @return bool
     * @throws Exception
     */
    public static function validateRetryErrors(stdClass $value): bool {
        foreach ($value as $k => $v) {
        }
        return true;
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function getRetryErrors(): stdClass {
        if (AuditCancelledPayload::validateRetryErrors($this->retryErrors))  {
            return $this->retryErrors;
        }
        throw new Exception('never get to getRetryErrors AuditCancelledPayload::retryErrors');
    }

    /**
     * @return stdClass
     */
    public static function sampleRetryErrors(): stdClass {
        return  (function () {
            $out = new stdClass();
            $out->{'AuditCancelledPayload'} = 'AnyType::AuditCancelledPayload::retryErrors::46';/*46:retryErrors*/
            return $out;
        })(); /* 46:retryErrors*/
    }

    /**
     * @param ?string $value
     * @throws Exception
     * @return ?string
     */
    public static function fromStatsPersistedAt(?string $value): ?string {
        if (!is_null($value)) {
            return $value; /*string*/
        } else {
            return  null;
        }
    }

    /**
     * @throws Exception
     * @return ?string
     */
    public function toStatsPersistedAt(): ?string {
        if (AuditCancelledPayload::validateStatsPersistedAt($this->statsPersistedAt))  {
            if (!is_null($this->statsPersistedAt)) {
                return $this->statsPersistedAt; /*string*/
            } else {
                return  null;
            }
        }
        throw new Exception('never get to this AuditCancelledPayload::statsPersistedAt');
    }

    /**
     * @param string|null
     * @return bool
     * @throws Exception
     */
    public static function validateStatsPersistedAt(?string $value): bool {
        if (!is_null($value)) {
            if (!is_string($value)) {
                throw new Exception("Attribute Error:AuditCancelledPayload::statsPersistedAt");
            }
        }
        return true;
    }

    /**
     * @throws Exception
     * @return ?string
     */
    public function getStatsPersistedAt(): ?string {
        if (AuditCancelledPayload::validateStatsPersistedAt($this->statsPersistedAt))  {
            return $this->statsPersistedAt;
        }
        throw new Exception('never get to getStatsPersistedAt AuditCancelledPayload::statsPersistedAt');
    }

    /**
     * @return ?string
     */
    public static function sampleStatsPersistedAt(): ?string {
        return 'AuditCancelledPayload::statsPersistedAt::47'; /*47:statsPersistedAt*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditCancelledPayload::validateAuditId($this->auditId)
        || AuditCancelledPayload::validateCrawlerFinishedAt($this->crawlerFinishedAt)
        || AuditCancelledPayload::validateCrawlerRuntimeMillis($this->crawlerRuntimeMillis)
        || AuditCancelledPayload::validateCrawlerStartedAt($this->crawlerStartedAt)
        || AuditCancelledPayload::validateErrors($this->errors)
        || AuditCancelledPayload::validateRequestMaxDurationMillis($this->requestMaxDurationMillis)
        || AuditCancelledPayload::validateRequestMinDurationMillis($this->requestMinDurationMillis)
        || AuditCancelledPayload::validateRequestsFailed($this->requestsFailed)
        || AuditCancelledPayload::validateRequestsFailedPerMinute($this->requestsFailedPerMinute)
        || AuditCancelledPayload::validateRequestsFinished($this->requestsFinished)
        || AuditCancelledPayload::validateRequestsFinishedPerMinute($this->requestsFinishedPerMinute)
        || AuditCancelledPayload::validateRequestsRetries($this->requestsRetries)
        || AuditCancelledPayload::validateRequestsWithStatusCode($this->requestsWithStatusCode)
        || AuditCancelledPayload::validateRequestTotalFailedDurationMillis($this->requestTotalFailedDurationMillis)
        || AuditCancelledPayload::validateRequestTotalFinishedDurationMillis($this->requestTotalFinishedDurationMillis)
        || AuditCancelledPayload::validateRetryErrors($this->retryErrors)
        || AuditCancelledPayload::validateStatsPersistedAt($this->statsPersistedAt);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'auditId'} = $this->toAuditId();
        $out->{'crawlerFinishedAt'} = $this->toCrawlerFinishedAt();
        $out->{'crawlerRuntimeMillis'} = $this->toCrawlerRuntimeMillis();
        $out->{'crawlerStartedAt'} = $this->toCrawlerStartedAt();
        $out->{'errors'} = $this->toErrors();
        $out->{'requestMaxDurationMillis'} = $this->toRequestMaxDurationMillis();
        $out->{'requestMinDurationMillis'} = $this->toRequestMinDurationMillis();
        $out->{'requestsFailed'} = $this->toRequestsFailed();
        $out->{'requestsFailedPerMinute'} = $this->toRequestsFailedPerMinute();
        $out->{'requestsFinished'} = $this->toRequestsFinished();
        $out->{'requestsFinishedPerMinute'} = $this->toRequestsFinishedPerMinute();
        $out->{'requestsRetries'} = $this->toRequestsRetries();
        $out->{'requestsWithStatusCode'} = $this->toRequestsWithStatusCode();
        $out->{'requestTotalFailedDurationMillis'} = $this->toRequestTotalFailedDurationMillis();
        $out->{'requestTotalFinishedDurationMillis'} = $this->toRequestTotalFinishedDurationMillis();
        $out->{'retryErrors'} = $this->toRetryErrors();
        $out->{'statsPersistedAt'} = $this->toStatsPersistedAt();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditCancelledPayload
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditCancelledPayload {
        return new AuditCancelledPayload(
         AuditCancelledPayload::fromAuditId($obj->{'auditId'})
        ,AuditCancelledPayload::fromCrawlerFinishedAt($obj->{'crawlerFinishedAt'})
        ,AuditCancelledPayload::fromCrawlerRuntimeMillis($obj->{'crawlerRuntimeMillis'})
        ,AuditCancelledPayload::fromCrawlerStartedAt($obj->{'crawlerStartedAt'})
        ,AuditCancelledPayload::fromErrors($obj->{'errors'})
        ,AuditCancelledPayload::fromRequestMaxDurationMillis($obj->{'requestMaxDurationMillis'})
        ,AuditCancelledPayload::fromRequestMinDurationMillis($obj->{'requestMinDurationMillis'})
        ,AuditCancelledPayload::fromRequestsFailed($obj->{'requestsFailed'})
        ,AuditCancelledPayload::fromRequestsFailedPerMinute($obj->{'requestsFailedPerMinute'})
        ,AuditCancelledPayload::fromRequestsFinished($obj->{'requestsFinished'})
        ,AuditCancelledPayload::fromRequestsFinishedPerMinute($obj->{'requestsFinishedPerMinute'})
        ,AuditCancelledPayload::fromRequestsRetries($obj->{'requestsRetries'})
        ,AuditCancelledPayload::fromRequestsWithStatusCode($obj->{'requestsWithStatusCode'})
        ,AuditCancelledPayload::fromRequestTotalFailedDurationMillis($obj->{'requestTotalFailedDurationMillis'})
        ,AuditCancelledPayload::fromRequestTotalFinishedDurationMillis($obj->{'requestTotalFinishedDurationMillis'})
        ,AuditCancelledPayload::fromRetryErrors($obj->{'retryErrors'})
        ,AuditCancelledPayload::fromStatsPersistedAt($obj->{'statsPersistedAt'})
        );
    }

    /**
     * @return AuditCancelledPayload
     */
    public static function sample(): AuditCancelledPayload {
        return new AuditCancelledPayload(
         AuditCancelledPayload::sampleAuditId()
        ,AuditCancelledPayload::sampleCrawlerFinishedAt()
        ,AuditCancelledPayload::sampleCrawlerRuntimeMillis()
        ,AuditCancelledPayload::sampleCrawlerStartedAt()
        ,AuditCancelledPayload::sampleErrors()
        ,AuditCancelledPayload::sampleRequestMaxDurationMillis()
        ,AuditCancelledPayload::sampleRequestMinDurationMillis()
        ,AuditCancelledPayload::sampleRequestsFailed()
        ,AuditCancelledPayload::sampleRequestsFailedPerMinute()
        ,AuditCancelledPayload::sampleRequestsFinished()
        ,AuditCancelledPayload::sampleRequestsFinishedPerMinute()
        ,AuditCancelledPayload::sampleRequestsRetries()
        ,AuditCancelledPayload::sampleRequestsWithStatusCode()
        ,AuditCancelledPayload::sampleRequestTotalFailedDurationMillis()
        ,AuditCancelledPayload::sampleRequestTotalFinishedDurationMillis()
        ,AuditCancelledPayload::sampleRetryErrors()
        ,AuditCancelledPayload::sampleStatsPersistedAt()
        );
    }
}

// This is an autogenerated file:AuditCancelledType

class AuditCancelledType {
    public static AuditCancelledType $AUDIT_CANCELLED;
    public static function init() {
        AuditCancelledType::$AUDIT_CANCELLED = new AuditCancelledType('audit.cancelled');
    }
    private string $enum;
    public function __construct(string $enum) {
        $this->enum = $enum;
    }

    /**
     * @param AuditCancelledType
     * @return string
     * @throws Exception
     */
    public static function to(AuditCancelledType $obj): string {
        switch ($obj->enum) {
            case AuditCancelledType::$AUDIT_CANCELLED->enum: return 'audit.cancelled';
        }
        throw new Exception('the give value is not an enum-value.');
    }

    /**
     * @param mixed
     * @return AuditCancelledType
     * @throws Exception
     */
    public static function from($obj): AuditCancelledType {
        switch ($obj) {
            case 'audit.cancelled': return AuditCancelledType::$AUDIT_CANCELLED;
        }
        throw new Exception("Cannot deserialize AuditCancelledType");
    }

    /**
     * @return AuditCancelledType
     */
    public static function sample(): AuditCancelledType {
        return AuditCancelledType::$AUDIT_CANCELLED;
    }
}
AuditCancelledType::init();
