<?php

namespace EqualSite\Events\Value;

use Exception;
use stdClass;

// This is an autogenerated file:AuditPageCompleted

class AuditPageCompleted {
    private AuditPageCompletedPayload $payload; // json:payload Required
    private int $timestamp; // json:timestamp Required
    private AuditPageCompletedType $type; // json:type Required
    private string $version; // json:version Required

    /**
     * @param AuditPageCompletedPayload $payload
     * @param int $timestamp
     * @param AuditPageCompletedType $type
     * @param string $version
     */
    public function __construct(AuditPageCompletedPayload $payload, int $timestamp, AuditPageCompletedType $type, string $version) {
        $this->payload = $payload;
        $this->timestamp = $timestamp;
        $this->type = $type;
        $this->version = $version;
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return AuditPageCompletedPayload
     */
    public static function fromPayload(stdClass $value): AuditPageCompletedPayload {
        return AuditPageCompletedPayload::from($value); /*class*/
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toPayload(): stdClass {
        if (AuditPageCompleted::validatePayload($this->payload))  {
            return $this->payload->to(); /*class*/
        }
        throw new Exception('never get to this AuditPageCompleted::payload');
    }

    /**
     * @param AuditPageCompletedPayload
     * @return bool
     * @throws Exception
     */
    public static function validatePayload(AuditPageCompletedPayload $value): bool {
        $value->validate();
        return true;
    }

    /**
     * @throws Exception
     * @return AuditPageCompletedPayload
     */
    public function getPayload(): AuditPageCompletedPayload {
        if (AuditPageCompleted::validatePayload($this->payload))  {
            return $this->payload;
        }
        throw new Exception('never get to getPayload AuditPageCompleted::payload');
    }

    /**
     * @return AuditPageCompletedPayload
     */
    public static function samplePayload(): AuditPageCompletedPayload {
        return AuditPageCompletedPayload::sample(); /*31:payload*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromTimestamp(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toTimestamp(): int {
        if (AuditPageCompleted::validateTimestamp($this->timestamp))  {
            return $this->timestamp; /*int*/
        }
        throw new Exception('never get to this AuditPageCompleted::timestamp');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateTimestamp(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditPageCompleted::timestamp");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getTimestamp(): int {
        if (AuditPageCompleted::validateTimestamp($this->timestamp))  {
            return $this->timestamp;
        }
        throw new Exception('never get to getTimestamp AuditPageCompleted::timestamp');
    }

    /**
     * @return int
     */
    public static function sampleTimestamp(): int {
        return 32; /*32:timestamp*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return AuditPageCompletedType
     */
    public static function fromType(string $value): AuditPageCompletedType {
        return AuditPageCompletedType::from($value); /*enum*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toType(): string {
        if (AuditPageCompleted::validateType($this->type))  {
            return AuditPageCompletedType::to($this->type); /*enum*/
        }
        throw new Exception('never get to this AuditPageCompleted::type');
    }

    /**
     * @param AuditPageCompletedType
     * @return bool
     * @throws Exception
     */
    public static function validateType(AuditPageCompletedType $value): bool {
        AuditPageCompletedType::to($value);
        return true;
    }

    /**
     * @throws Exception
     * @return AuditPageCompletedType
     */
    public function getType(): AuditPageCompletedType {
        if (AuditPageCompleted::validateType($this->type))  {
            return $this->type;
        }
        throw new Exception('never get to getType AuditPageCompleted::type');
    }

    /**
     * @return AuditPageCompletedType
     */
    public static function sampleType(): AuditPageCompletedType {
        return AuditPageCompletedType::sample(); /*enum*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromVersion(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toVersion(): string {
        if (AuditPageCompleted::validateVersion($this->version))  {
            return $this->version; /*string*/
        }
        throw new Exception('never get to this AuditPageCompleted::version');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateVersion(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditPageCompleted::version");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getVersion(): string {
        if (AuditPageCompleted::validateVersion($this->version))  {
            return $this->version;
        }
        throw new Exception('never get to getVersion AuditPageCompleted::version');
    }

    /**
     * @return string
     */
    public static function sampleVersion(): string {
        return 'AuditPageCompleted::version::34'; /*34:version*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditPageCompleted::validatePayload($this->payload)
        || AuditPageCompleted::validateTimestamp($this->timestamp)
        || AuditPageCompleted::validateType($this->type)
        || AuditPageCompleted::validateVersion($this->version);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'payload'} = $this->toPayload();
        $out->{'timestamp'} = $this->toTimestamp();
        $out->{'type'} = $this->toType();
        $out->{'version'} = $this->toVersion();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditPageCompleted
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditPageCompleted {
        return new AuditPageCompleted(
         AuditPageCompleted::fromPayload($obj->{'payload'})
        ,AuditPageCompleted::fromTimestamp($obj->{'timestamp'})
        ,AuditPageCompleted::fromType($obj->{'type'})
        ,AuditPageCompleted::fromVersion($obj->{'version'})
        );
    }

    /**
     * @return AuditPageCompleted
     */
    public static function sample(): AuditPageCompleted {
        return new AuditPageCompleted(
         AuditPageCompleted::samplePayload()
        ,AuditPageCompleted::sampleTimestamp()
        ,AuditPageCompleted::sampleType()
        ,AuditPageCompleted::sampleVersion()
        );
    }
}

// This is an autogenerated file:AuditPageCompletedPayload

class AuditPageCompletedPayload {
    private string $auditId; // json:auditId Required
    private string $pageUrl; // json:pageUrl Required
    private ?int $passesCount; // json:passesCount Optional
    private AuditPageCompletedSeverityBreakdown $severityBreakdown; // json:severityBreakdown Required
    private int $violationsCount; // json:violationsCount Required

    /**
     * @param string $auditId
     * @param string $pageUrl
     * @param int|null $passesCount
     * @param AuditPageCompletedSeverityBreakdown $severityBreakdown
     * @param int $violationsCount
     */
    public function __construct(string $auditId, string $pageUrl, ?int $passesCount, AuditPageCompletedSeverityBreakdown $severityBreakdown, int $violationsCount) {
        $this->auditId = $auditId;
        $this->pageUrl = $pageUrl;
        $this->passesCount = $passesCount;
        $this->severityBreakdown = $severityBreakdown;
        $this->violationsCount = $violationsCount;
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromAuditId(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toAuditId(): string {
        if (AuditPageCompletedPayload::validateAuditId($this->auditId))  {
            return $this->auditId; /*string*/
        }
        throw new Exception('never get to this AuditPageCompletedPayload::auditId');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateAuditId(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditPageCompletedPayload::auditId");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getAuditId(): string {
        if (AuditPageCompletedPayload::validateAuditId($this->auditId))  {
            return $this->auditId;
        }
        throw new Exception('never get to getAuditId AuditPageCompletedPayload::auditId');
    }

    /**
     * @return string
     */
    public static function sampleAuditId(): string {
        return 'AuditPageCompletedPayload::auditId::31'; /*31:auditId*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromPageUrl(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toPageUrl(): string {
        if (AuditPageCompletedPayload::validatePageUrl($this->pageUrl))  {
            return $this->pageUrl; /*string*/
        }
        throw new Exception('never get to this AuditPageCompletedPayload::pageUrl');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validatePageUrl(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditPageCompletedPayload::pageUrl");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getPageUrl(): string {
        if (AuditPageCompletedPayload::validatePageUrl($this->pageUrl))  {
            return $this->pageUrl;
        }
        throw new Exception('never get to getPageUrl AuditPageCompletedPayload::pageUrl');
    }

    /**
     * @return string
     */
    public static function samplePageUrl(): string {
        return 'AuditPageCompletedPayload::pageUrl::32'; /*32:pageUrl*/
    }

    /**
     * @param ?int $value
     * @throws Exception
     * @return ?int
     */
    public static function fromPassesCount(?int $value): ?int {
        if (!is_null($value)) {
            return $value; /*int*/
        } else {
            return  null;
        }
    }

    /**
     * @throws Exception
     * @return ?int
     */
    public function toPassesCount(): ?int {
        if (AuditPageCompletedPayload::validatePassesCount($this->passesCount))  {
            if (!is_null($this->passesCount)) {
                return $this->passesCount; /*int*/
            } else {
                return  null;
            }
        }
        throw new Exception('never get to this AuditPageCompletedPayload::passesCount');
    }

    /**
     * @param int|null
     * @return bool
     * @throws Exception
     */
    public static function validatePassesCount(?int $value): bool {
        if (!is_null($value)) {
            if (!is_integer($value)) {
                throw new Exception("Attribute Error:AuditPageCompletedPayload::passesCount");
            }
        }
        return true;
    }

    /**
     * @throws Exception
     * @return ?int
     */
    public function getPassesCount(): ?int {
        if (AuditPageCompletedPayload::validatePassesCount($this->passesCount))  {
            return $this->passesCount;
        }
        throw new Exception('never get to getPassesCount AuditPageCompletedPayload::passesCount');
    }

    /**
     * @return ?int
     */
    public static function samplePassesCount(): ?int {
        return 33; /*33:passesCount*/
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return AuditPageCompletedSeverityBreakdown
     */
    public static function fromSeverityBreakdown(stdClass $value): AuditPageCompletedSeverityBreakdown {
        return AuditPageCompletedSeverityBreakdown::from($value); /*class*/
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toSeverityBreakdown(): stdClass {
        if (AuditPageCompletedPayload::validateSeverityBreakdown($this->severityBreakdown))  {
            return $this->severityBreakdown->to(); /*class*/
        }
        throw new Exception('never get to this AuditPageCompletedPayload::severityBreakdown');
    }

    /**
     * @param AuditPageCompletedSeverityBreakdown
     * @return bool
     * @throws Exception
     */
    public static function validateSeverityBreakdown(AuditPageCompletedSeverityBreakdown $value): bool {
        $value->validate();
        return true;
    }

    /**
     * @throws Exception
     * @return AuditPageCompletedSeverityBreakdown
     */
    public function getSeverityBreakdown(): AuditPageCompletedSeverityBreakdown {
        if (AuditPageCompletedPayload::validateSeverityBreakdown($this->severityBreakdown))  {
            return $this->severityBreakdown;
        }
        throw new Exception('never get to getSeverityBreakdown AuditPageCompletedPayload::severityBreakdown');
    }

    /**
     * @return AuditPageCompletedSeverityBreakdown
     */
    public static function sampleSeverityBreakdown(): AuditPageCompletedSeverityBreakdown {
        return AuditPageCompletedSeverityBreakdown::sample(); /*34:severityBreakdown*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromViolationsCount(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toViolationsCount(): int {
        if (AuditPageCompletedPayload::validateViolationsCount($this->violationsCount))  {
            return $this->violationsCount; /*int*/
        }
        throw new Exception('never get to this AuditPageCompletedPayload::violationsCount');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateViolationsCount(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditPageCompletedPayload::violationsCount");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getViolationsCount(): int {
        if (AuditPageCompletedPayload::validateViolationsCount($this->violationsCount))  {
            return $this->violationsCount;
        }
        throw new Exception('never get to getViolationsCount AuditPageCompletedPayload::violationsCount');
    }

    /**
     * @return int
     */
    public static function sampleViolationsCount(): int {
        return 35; /*35:violationsCount*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditPageCompletedPayload::validateAuditId($this->auditId)
        || AuditPageCompletedPayload::validatePageUrl($this->pageUrl)
        || AuditPageCompletedPayload::validatePassesCount($this->passesCount)
        || AuditPageCompletedPayload::validateSeverityBreakdown($this->severityBreakdown)
        || AuditPageCompletedPayload::validateViolationsCount($this->violationsCount);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'auditId'} = $this->toAuditId();
        $out->{'pageUrl'} = $this->toPageUrl();
        $out->{'passesCount'} = $this->toPassesCount();
        $out->{'severityBreakdown'} = $this->toSeverityBreakdown();
        $out->{'violationsCount'} = $this->toViolationsCount();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditPageCompletedPayload
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditPageCompletedPayload {
        return new AuditPageCompletedPayload(
         AuditPageCompletedPayload::fromAuditId($obj->{'auditId'})
        ,AuditPageCompletedPayload::fromPageUrl($obj->{'pageUrl'})
        ,AuditPageCompletedPayload::fromPassesCount($obj->{'passesCount'})
        ,AuditPageCompletedPayload::fromSeverityBreakdown($obj->{'severityBreakdown'})
        ,AuditPageCompletedPayload::fromViolationsCount($obj->{'violationsCount'})
        );
    }

    /**
     * @return AuditPageCompletedPayload
     */
    public static function sample(): AuditPageCompletedPayload {
        return new AuditPageCompletedPayload(
         AuditPageCompletedPayload::sampleAuditId()
        ,AuditPageCompletedPayload::samplePageUrl()
        ,AuditPageCompletedPayload::samplePassesCount()
        ,AuditPageCompletedPayload::sampleSeverityBreakdown()
        ,AuditPageCompletedPayload::sampleViolationsCount()
        );
    }
}

// This is an autogenerated file:AuditPageCompletedSeverityBreakdown

class AuditPageCompletedSeverityBreakdown {
    private int $critical; // json:critical Required
    private int $minor; // json:minor Required
    private int $moderate; // json:moderate Required
    private int $serious; // json:serious Required

    /**
     * @param int $critical
     * @param int $minor
     * @param int $moderate
     * @param int $serious
     */
    public function __construct(int $critical, int $minor, int $moderate, int $serious) {
        $this->critical = $critical;
        $this->minor = $minor;
        $this->moderate = $moderate;
        $this->serious = $serious;
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromCritical(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toCritical(): int {
        if (AuditPageCompletedSeverityBreakdown::validateCritical($this->critical))  {
            return $this->critical; /*int*/
        }
        throw new Exception('never get to this AuditPageCompletedSeverityBreakdown::critical');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateCritical(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditPageCompletedSeverityBreakdown::critical");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getCritical(): int {
        if (AuditPageCompletedSeverityBreakdown::validateCritical($this->critical))  {
            return $this->critical;
        }
        throw new Exception('never get to getCritical AuditPageCompletedSeverityBreakdown::critical');
    }

    /**
     * @return int
     */
    public static function sampleCritical(): int {
        return 31; /*31:critical*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromMinor(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toMinor(): int {
        if (AuditPageCompletedSeverityBreakdown::validateMinor($this->minor))  {
            return $this->minor; /*int*/
        }
        throw new Exception('never get to this AuditPageCompletedSeverityBreakdown::minor');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateMinor(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditPageCompletedSeverityBreakdown::minor");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getMinor(): int {
        if (AuditPageCompletedSeverityBreakdown::validateMinor($this->minor))  {
            return $this->minor;
        }
        throw new Exception('never get to getMinor AuditPageCompletedSeverityBreakdown::minor');
    }

    /**
     * @return int
     */
    public static function sampleMinor(): int {
        return 32; /*32:minor*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromModerate(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toModerate(): int {
        if (AuditPageCompletedSeverityBreakdown::validateModerate($this->moderate))  {
            return $this->moderate; /*int*/
        }
        throw new Exception('never get to this AuditPageCompletedSeverityBreakdown::moderate');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateModerate(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditPageCompletedSeverityBreakdown::moderate");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getModerate(): int {
        if (AuditPageCompletedSeverityBreakdown::validateModerate($this->moderate))  {
            return $this->moderate;
        }
        throw new Exception('never get to getModerate AuditPageCompletedSeverityBreakdown::moderate');
    }

    /**
     * @return int
     */
    public static function sampleModerate(): int {
        return 33; /*33:moderate*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromSerious(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toSerious(): int {
        if (AuditPageCompletedSeverityBreakdown::validateSerious($this->serious))  {
            return $this->serious; /*int*/
        }
        throw new Exception('never get to this AuditPageCompletedSeverityBreakdown::serious');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateSerious(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditPageCompletedSeverityBreakdown::serious");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getSerious(): int {
        if (AuditPageCompletedSeverityBreakdown::validateSerious($this->serious))  {
            return $this->serious;
        }
        throw new Exception('never get to getSerious AuditPageCompletedSeverityBreakdown::serious');
    }

    /**
     * @return int
     */
    public static function sampleSerious(): int {
        return 34; /*34:serious*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditPageCompletedSeverityBreakdown::validateCritical($this->critical)
        || AuditPageCompletedSeverityBreakdown::validateMinor($this->minor)
        || AuditPageCompletedSeverityBreakdown::validateModerate($this->moderate)
        || AuditPageCompletedSeverityBreakdown::validateSerious($this->serious);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'critical'} = $this->toCritical();
        $out->{'minor'} = $this->toMinor();
        $out->{'moderate'} = $this->toModerate();
        $out->{'serious'} = $this->toSerious();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditPageCompletedSeverityBreakdown
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditPageCompletedSeverityBreakdown {
        return new AuditPageCompletedSeverityBreakdown(
         AuditPageCompletedSeverityBreakdown::fromCritical($obj->{'critical'})
        ,AuditPageCompletedSeverityBreakdown::fromMinor($obj->{'minor'})
        ,AuditPageCompletedSeverityBreakdown::fromModerate($obj->{'moderate'})
        ,AuditPageCompletedSeverityBreakdown::fromSerious($obj->{'serious'})
        );
    }

    /**
     * @return AuditPageCompletedSeverityBreakdown
     */
    public static function sample(): AuditPageCompletedSeverityBreakdown {
        return new AuditPageCompletedSeverityBreakdown(
         AuditPageCompletedSeverityBreakdown::sampleCritical()
        ,AuditPageCompletedSeverityBreakdown::sampleMinor()
        ,AuditPageCompletedSeverityBreakdown::sampleModerate()
        ,AuditPageCompletedSeverityBreakdown::sampleSerious()
        );
    }
}

// This is an autogenerated file:AuditPageCompletedType

class AuditPageCompletedType {
    public static AuditPageCompletedType $AUDIT_PAGE_COMPLETED;
    public static function init() {
        AuditPageCompletedType::$AUDIT_PAGE_COMPLETED = new AuditPageCompletedType('audit.page.completed');
    }
    private string $enum;
    public function __construct(string $enum) {
        $this->enum = $enum;
    }

    /**
     * @param AuditPageCompletedType
     * @return string
     * @throws Exception
     */
    public static function to(AuditPageCompletedType $obj): string {
        switch ($obj->enum) {
            case AuditPageCompletedType::$AUDIT_PAGE_COMPLETED->enum: return 'audit.page.completed';
        }
        throw new Exception('the give value is not an enum-value.');
    }

    /**
     * @param mixed
     * @return AuditPageCompletedType
     * @throws Exception
     */
    public static function from($obj): AuditPageCompletedType {
        switch ($obj) {
            case 'audit.page.completed': return AuditPageCompletedType::$AUDIT_PAGE_COMPLETED;
        }
        throw new Exception("Cannot deserialize AuditPageCompletedType");
    }

    /**
     * @return AuditPageCompletedType
     */
    public static function sample(): AuditPageCompletedType {
        return AuditPageCompletedType::$AUDIT_PAGE_COMPLETED;
    }
}
AuditPageCompletedType::init();
