<?php

namespace EqualSite\Events\Value;

use Exception;
use stdClass;

// This is an autogenerated file:AuditPageStarted

class AuditPageStarted {
    private AuditPageStartedPayload $payload; // json:payload Required
    private int $timestamp; // json:timestamp Required
    private AuditPageStartedType $type; // json:type Required
    private string $version; // json:version Required

    /**
     * @param AuditPageStartedPayload $payload
     * @param int $timestamp
     * @param AuditPageStartedType $type
     * @param string $version
     */
    public function __construct(AuditPageStartedPayload $payload, int $timestamp, AuditPageStartedType $type, string $version) {
        $this->payload = $payload;
        $this->timestamp = $timestamp;
        $this->type = $type;
        $this->version = $version;
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return AuditPageStartedPayload
     */
    public static function fromPayload(stdClass $value): AuditPageStartedPayload {
        return AuditPageStartedPayload::from($value); /*class*/
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toPayload(): stdClass {
        if (AuditPageStarted::validatePayload($this->payload))  {
            return $this->payload->to(); /*class*/
        }
        throw new Exception('never get to this AuditPageStarted::payload');
    }

    /**
     * @param AuditPageStartedPayload
     * @return bool
     * @throws Exception
     */
    public static function validatePayload(AuditPageStartedPayload $value): bool {
        $value->validate();
        return true;
    }

    /**
     * @throws Exception
     * @return AuditPageStartedPayload
     */
    public function getPayload(): AuditPageStartedPayload {
        if (AuditPageStarted::validatePayload($this->payload))  {
            return $this->payload;
        }
        throw new Exception('never get to getPayload AuditPageStarted::payload');
    }

    /**
     * @return AuditPageStartedPayload
     */
    public static function samplePayload(): AuditPageStartedPayload {
        return AuditPageStartedPayload::sample(); /*31:payload*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromTimestamp(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toTimestamp(): int {
        if (AuditPageStarted::validateTimestamp($this->timestamp))  {
            return $this->timestamp; /*int*/
        }
        throw new Exception('never get to this AuditPageStarted::timestamp');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateTimestamp(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditPageStarted::timestamp");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getTimestamp(): int {
        if (AuditPageStarted::validateTimestamp($this->timestamp))  {
            return $this->timestamp;
        }
        throw new Exception('never get to getTimestamp AuditPageStarted::timestamp');
    }

    /**
     * @return int
     */
    public static function sampleTimestamp(): int {
        return 32; /*32:timestamp*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return AuditPageStartedType
     */
    public static function fromType(string $value): AuditPageStartedType {
        return AuditPageStartedType::from($value); /*enum*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toType(): string {
        if (AuditPageStarted::validateType($this->type))  {
            return AuditPageStartedType::to($this->type); /*enum*/
        }
        throw new Exception('never get to this AuditPageStarted::type');
    }

    /**
     * @param AuditPageStartedType
     * @return bool
     * @throws Exception
     */
    public static function validateType(AuditPageStartedType $value): bool {
        AuditPageStartedType::to($value);
        return true;
    }

    /**
     * @throws Exception
     * @return AuditPageStartedType
     */
    public function getType(): AuditPageStartedType {
        if (AuditPageStarted::validateType($this->type))  {
            return $this->type;
        }
        throw new Exception('never get to getType AuditPageStarted::type');
    }

    /**
     * @return AuditPageStartedType
     */
    public static function sampleType(): AuditPageStartedType {
        return AuditPageStartedType::sample(); /*enum*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromVersion(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toVersion(): string {
        if (AuditPageStarted::validateVersion($this->version))  {
            return $this->version; /*string*/
        }
        throw new Exception('never get to this AuditPageStarted::version');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateVersion(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditPageStarted::version");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getVersion(): string {
        if (AuditPageStarted::validateVersion($this->version))  {
            return $this->version;
        }
        throw new Exception('never get to getVersion AuditPageStarted::version');
    }

    /**
     * @return string
     */
    public static function sampleVersion(): string {
        return 'AuditPageStarted::version::34'; /*34:version*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditPageStarted::validatePayload($this->payload)
        || AuditPageStarted::validateTimestamp($this->timestamp)
        || AuditPageStarted::validateType($this->type)
        || AuditPageStarted::validateVersion($this->version);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'payload'} = $this->toPayload();
        $out->{'timestamp'} = $this->toTimestamp();
        $out->{'type'} = $this->toType();
        $out->{'version'} = $this->toVersion();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditPageStarted
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditPageStarted {
        return new AuditPageStarted(
         AuditPageStarted::fromPayload($obj->{'payload'})
        ,AuditPageStarted::fromTimestamp($obj->{'timestamp'})
        ,AuditPageStarted::fromType($obj->{'type'})
        ,AuditPageStarted::fromVersion($obj->{'version'})
        );
    }

    /**
     * @return AuditPageStarted
     */
    public static function sample(): AuditPageStarted {
        return new AuditPageStarted(
         AuditPageStarted::samplePayload()
        ,AuditPageStarted::sampleTimestamp()
        ,AuditPageStarted::sampleType()
        ,AuditPageStarted::sampleVersion()
        );
    }
}

// This is an autogenerated file:AuditPageStartedPayload

class AuditPageStartedPayload {
    private int $attemptsCount; // json:attemptsCount Required
    private string $auditId; // json:auditId Required
    private string $pageUrl; // json:pageUrl Required

    /**
     * @param int $attemptsCount
     * @param string $auditId
     * @param string $pageUrl
     */
    public function __construct(int $attemptsCount, string $auditId, string $pageUrl) {
        $this->attemptsCount = $attemptsCount;
        $this->auditId = $auditId;
        $this->pageUrl = $pageUrl;
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromAttemptsCount(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toAttemptsCount(): int {
        if (AuditPageStartedPayload::validateAttemptsCount($this->attemptsCount))  {
            return $this->attemptsCount; /*int*/
        }
        throw new Exception('never get to this AuditPageStartedPayload::attemptsCount');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateAttemptsCount(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditPageStartedPayload::attemptsCount");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getAttemptsCount(): int {
        if (AuditPageStartedPayload::validateAttemptsCount($this->attemptsCount))  {
            return $this->attemptsCount;
        }
        throw new Exception('never get to getAttemptsCount AuditPageStartedPayload::attemptsCount');
    }

    /**
     * @return int
     */
    public static function sampleAttemptsCount(): int {
        return 31; /*31:attemptsCount*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromAuditId(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toAuditId(): string {
        if (AuditPageStartedPayload::validateAuditId($this->auditId))  {
            return $this->auditId; /*string*/
        }
        throw new Exception('never get to this AuditPageStartedPayload::auditId');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateAuditId(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditPageStartedPayload::auditId");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getAuditId(): string {
        if (AuditPageStartedPayload::validateAuditId($this->auditId))  {
            return $this->auditId;
        }
        throw new Exception('never get to getAuditId AuditPageStartedPayload::auditId');
    }

    /**
     * @return string
     */
    public static function sampleAuditId(): string {
        return 'AuditPageStartedPayload::auditId::32'; /*32:auditId*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromPageUrl(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toPageUrl(): string {
        if (AuditPageStartedPayload::validatePageUrl($this->pageUrl))  {
            return $this->pageUrl; /*string*/
        }
        throw new Exception('never get to this AuditPageStartedPayload::pageUrl');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validatePageUrl(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditPageStartedPayload::pageUrl");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getPageUrl(): string {
        if (AuditPageStartedPayload::validatePageUrl($this->pageUrl))  {
            return $this->pageUrl;
        }
        throw new Exception('never get to getPageUrl AuditPageStartedPayload::pageUrl');
    }

    /**
     * @return string
     */
    public static function samplePageUrl(): string {
        return 'AuditPageStartedPayload::pageUrl::33'; /*33:pageUrl*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditPageStartedPayload::validateAttemptsCount($this->attemptsCount)
        || AuditPageStartedPayload::validateAuditId($this->auditId)
        || AuditPageStartedPayload::validatePageUrl($this->pageUrl);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'attemptsCount'} = $this->toAttemptsCount();
        $out->{'auditId'} = $this->toAuditId();
        $out->{'pageUrl'} = $this->toPageUrl();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditPageStartedPayload
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditPageStartedPayload {
        return new AuditPageStartedPayload(
         AuditPageStartedPayload::fromAttemptsCount($obj->{'attemptsCount'})
        ,AuditPageStartedPayload::fromAuditId($obj->{'auditId'})
        ,AuditPageStartedPayload::fromPageUrl($obj->{'pageUrl'})
        );
    }

    /**
     * @return AuditPageStartedPayload
     */
    public static function sample(): AuditPageStartedPayload {
        return new AuditPageStartedPayload(
         AuditPageStartedPayload::sampleAttemptsCount()
        ,AuditPageStartedPayload::sampleAuditId()
        ,AuditPageStartedPayload::samplePageUrl()
        );
    }
}

// This is an autogenerated file:AuditPageStartedType

class AuditPageStartedType {
    public static AuditPageStartedType $AUDIT_PAGE_STARTED;
    public static function init() {
        AuditPageStartedType::$AUDIT_PAGE_STARTED = new AuditPageStartedType('audit.page.started');
    }
    private string $enum;
    public function __construct(string $enum) {
        $this->enum = $enum;
    }

    /**
     * @param AuditPageStartedType
     * @return string
     * @throws Exception
     */
    public static function to(AuditPageStartedType $obj): string {
        switch ($obj->enum) {
            case AuditPageStartedType::$AUDIT_PAGE_STARTED->enum: return 'audit.page.started';
        }
        throw new Exception('the give value is not an enum-value.');
    }

    /**
     * @param mixed
     * @return AuditPageStartedType
     * @throws Exception
     */
    public static function from($obj): AuditPageStartedType {
        switch ($obj) {
            case 'audit.page.started': return AuditPageStartedType::$AUDIT_PAGE_STARTED;
        }
        throw new Exception("Cannot deserialize AuditPageStartedType");
    }

    /**
     * @return AuditPageStartedType
     */
    public static function sample(): AuditPageStartedType {
        return AuditPageStartedType::$AUDIT_PAGE_STARTED;
    }
}
AuditPageStartedType::init();
