<?php

namespace EqualSite\Events\Value;

use Exception;
use stdClass;

// This is an autogenerated file:AuditStarted

class AuditStarted {
    private AuditStartedPayload $payload; // json:payload Required
    private int $timestamp; // json:timestamp Required
    private AuditStartedType $type; // json:type Required
    private string $version; // json:version Required

    /**
     * @param AuditStartedPayload $payload
     * @param int $timestamp
     * @param AuditStartedType $type
     * @param string $version
     */
    public function __construct(AuditStartedPayload $payload, int $timestamp, AuditStartedType $type, string $version) {
        $this->payload = $payload;
        $this->timestamp = $timestamp;
        $this->type = $type;
        $this->version = $version;
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return AuditStartedPayload
     */
    public static function fromPayload(stdClass $value): AuditStartedPayload {
        return AuditStartedPayload::from($value); /*class*/
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toPayload(): stdClass {
        if (AuditStarted::validatePayload($this->payload))  {
            return $this->payload->to(); /*class*/
        }
        throw new Exception('never get to this AuditStarted::payload');
    }

    /**
     * @param AuditStartedPayload
     * @return bool
     * @throws Exception
     */
    public static function validatePayload(AuditStartedPayload $value): bool {
        $value->validate();
        return true;
    }

    /**
     * @throws Exception
     * @return AuditStartedPayload
     */
    public function getPayload(): AuditStartedPayload {
        if (AuditStarted::validatePayload($this->payload))  {
            return $this->payload;
        }
        throw new Exception('never get to getPayload AuditStarted::payload');
    }

    /**
     * @return AuditStartedPayload
     */
    public static function samplePayload(): AuditStartedPayload {
        return AuditStartedPayload::sample(); /*31:payload*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromTimestamp(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toTimestamp(): int {
        if (AuditStarted::validateTimestamp($this->timestamp))  {
            return $this->timestamp; /*int*/
        }
        throw new Exception('never get to this AuditStarted::timestamp');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateTimestamp(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditStarted::timestamp");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getTimestamp(): int {
        if (AuditStarted::validateTimestamp($this->timestamp))  {
            return $this->timestamp;
        }
        throw new Exception('never get to getTimestamp AuditStarted::timestamp');
    }

    /**
     * @return int
     */
    public static function sampleTimestamp(): int {
        return 32; /*32:timestamp*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return AuditStartedType
     */
    public static function fromType(string $value): AuditStartedType {
        return AuditStartedType::from($value); /*enum*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toType(): string {
        if (AuditStarted::validateType($this->type))  {
            return AuditStartedType::to($this->type); /*enum*/
        }
        throw new Exception('never get to this AuditStarted::type');
    }

    /**
     * @param AuditStartedType
     * @return bool
     * @throws Exception
     */
    public static function validateType(AuditStartedType $value): bool {
        AuditStartedType::to($value);
        return true;
    }

    /**
     * @throws Exception
     * @return AuditStartedType
     */
    public function getType(): AuditStartedType {
        if (AuditStarted::validateType($this->type))  {
            return $this->type;
        }
        throw new Exception('never get to getType AuditStarted::type');
    }

    /**
     * @return AuditStartedType
     */
    public static function sampleType(): AuditStartedType {
        return AuditStartedType::sample(); /*enum*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromVersion(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toVersion(): string {
        if (AuditStarted::validateVersion($this->version))  {
            return $this->version; /*string*/
        }
        throw new Exception('never get to this AuditStarted::version');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateVersion(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditStarted::version");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getVersion(): string {
        if (AuditStarted::validateVersion($this->version))  {
            return $this->version;
        }
        throw new Exception('never get to getVersion AuditStarted::version');
    }

    /**
     * @return string
     */
    public static function sampleVersion(): string {
        return 'AuditStarted::version::34'; /*34:version*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditStarted::validatePayload($this->payload)
        || AuditStarted::validateTimestamp($this->timestamp)
        || AuditStarted::validateType($this->type)
        || AuditStarted::validateVersion($this->version);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'payload'} = $this->toPayload();
        $out->{'timestamp'} = $this->toTimestamp();
        $out->{'type'} = $this->toType();
        $out->{'version'} = $this->toVersion();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditStarted
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditStarted {
        return new AuditStarted(
         AuditStarted::fromPayload($obj->{'payload'})
        ,AuditStarted::fromTimestamp($obj->{'timestamp'})
        ,AuditStarted::fromType($obj->{'type'})
        ,AuditStarted::fromVersion($obj->{'version'})
        );
    }

    /**
     * @return AuditStarted
     */
    public static function sample(): AuditStarted {
        return new AuditStarted(
         AuditStarted::samplePayload()
        ,AuditStarted::sampleTimestamp()
        ,AuditStarted::sampleType()
        ,AuditStarted::sampleVersion()
        );
    }
}

// This is an autogenerated file:AuditStartedPayload

class AuditStartedPayload {
    private string $auditId; // json:auditId Required

    /**
     * @param string $auditId
     */
    public function __construct(string $auditId) {
        $this->auditId = $auditId;
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromAuditId(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toAuditId(): string {
        if (AuditStartedPayload::validateAuditId($this->auditId))  {
            return $this->auditId; /*string*/
        }
        throw new Exception('never get to this AuditStartedPayload::auditId');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateAuditId(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditStartedPayload::auditId");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getAuditId(): string {
        if (AuditStartedPayload::validateAuditId($this->auditId))  {
            return $this->auditId;
        }
        throw new Exception('never get to getAuditId AuditStartedPayload::auditId');
    }

    /**
     * @return string
     */
    public static function sampleAuditId(): string {
        return 'AuditStartedPayload::auditId::31'; /*31:auditId*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditStartedPayload::validateAuditId($this->auditId);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'auditId'} = $this->toAuditId();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditStartedPayload
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditStartedPayload {
        return new AuditStartedPayload(
         AuditStartedPayload::fromAuditId($obj->{'auditId'})
        );
    }

    /**
     * @return AuditStartedPayload
     */
    public static function sample(): AuditStartedPayload {
        return new AuditStartedPayload(
         AuditStartedPayload::sampleAuditId()
        );
    }
}

// This is an autogenerated file:AuditStartedType

class AuditStartedType {
    public static AuditStartedType $AUDIT_STARTED;
    public static function init() {
        AuditStartedType::$AUDIT_STARTED = new AuditStartedType('audit.started');
    }
    private string $enum;
    public function __construct(string $enum) {
        $this->enum = $enum;
    }

    /**
     * @param AuditStartedType
     * @return string
     * @throws Exception
     */
    public static function to(AuditStartedType $obj): string {
        switch ($obj->enum) {
            case AuditStartedType::$AUDIT_STARTED->enum: return 'audit.started';
        }
        throw new Exception('the give value is not an enum-value.');
    }

    /**
     * @param mixed
     * @return AuditStartedType
     * @throws Exception
     */
    public static function from($obj): AuditStartedType {
        switch ($obj) {
            case 'audit.started': return AuditStartedType::$AUDIT_STARTED;
        }
        throw new Exception("Cannot deserialize AuditStartedType");
    }

    /**
     * @return AuditStartedType
     */
    public static function sample(): AuditStartedType {
        return AuditStartedType::$AUDIT_STARTED;
    }
}
AuditStartedType::init();
