<?php

namespace EqualSite\Events\Value;

use Exception;
use stdClass;

// This is an autogenerated file:AuditPageFailed

class AuditPageFailed {
    private AuditPageFailedPayload $payload; // json:payload Required
    private int $timestamp; // json:timestamp Required
    private AuditPageFailedType $type; // json:type Required
    private string $version; // json:version Required

    /**
     * @param AuditPageFailedPayload $payload
     * @param int $timestamp
     * @param AuditPageFailedType $type
     * @param string $version
     */
    public function __construct(AuditPageFailedPayload $payload, int $timestamp, AuditPageFailedType $type, string $version) {
        $this->payload = $payload;
        $this->timestamp = $timestamp;
        $this->type = $type;
        $this->version = $version;
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return AuditPageFailedPayload
     */
    public static function fromPayload(stdClass $value): AuditPageFailedPayload {
        return AuditPageFailedPayload::from($value); /*class*/
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toPayload(): stdClass {
        if (AuditPageFailed::validatePayload($this->payload))  {
            return $this->payload->to(); /*class*/
        }
        throw new Exception('never get to this AuditPageFailed::payload');
    }

    /**
     * @param AuditPageFailedPayload
     * @return bool
     * @throws Exception
     */
    public static function validatePayload(AuditPageFailedPayload $value): bool {
        $value->validate();
        return true;
    }

    /**
     * @throws Exception
     * @return AuditPageFailedPayload
     */
    public function getPayload(): AuditPageFailedPayload {
        if (AuditPageFailed::validatePayload($this->payload))  {
            return $this->payload;
        }
        throw new Exception('never get to getPayload AuditPageFailed::payload');
    }

    /**
     * @return AuditPageFailedPayload
     */
    public static function samplePayload(): AuditPageFailedPayload {
        return AuditPageFailedPayload::sample(); /*31:payload*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromTimestamp(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toTimestamp(): int {
        if (AuditPageFailed::validateTimestamp($this->timestamp))  {
            return $this->timestamp; /*int*/
        }
        throw new Exception('never get to this AuditPageFailed::timestamp');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateTimestamp(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditPageFailed::timestamp");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getTimestamp(): int {
        if (AuditPageFailed::validateTimestamp($this->timestamp))  {
            return $this->timestamp;
        }
        throw new Exception('never get to getTimestamp AuditPageFailed::timestamp');
    }

    /**
     * @return int
     */
    public static function sampleTimestamp(): int {
        return 32; /*32:timestamp*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return AuditPageFailedType
     */
    public static function fromType(string $value): AuditPageFailedType {
        return AuditPageFailedType::from($value); /*enum*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toType(): string {
        if (AuditPageFailed::validateType($this->type))  {
            return AuditPageFailedType::to($this->type); /*enum*/
        }
        throw new Exception('never get to this AuditPageFailed::type');
    }

    /**
     * @param AuditPageFailedType
     * @return bool
     * @throws Exception
     */
    public static function validateType(AuditPageFailedType $value): bool {
        AuditPageFailedType::to($value);
        return true;
    }

    /**
     * @throws Exception
     * @return AuditPageFailedType
     */
    public function getType(): AuditPageFailedType {
        if (AuditPageFailed::validateType($this->type))  {
            return $this->type;
        }
        throw new Exception('never get to getType AuditPageFailed::type');
    }

    /**
     * @return AuditPageFailedType
     */
    public static function sampleType(): AuditPageFailedType {
        return AuditPageFailedType::sample(); /*enum*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromVersion(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toVersion(): string {
        if (AuditPageFailed::validateVersion($this->version))  {
            return $this->version; /*string*/
        }
        throw new Exception('never get to this AuditPageFailed::version');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateVersion(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditPageFailed::version");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getVersion(): string {
        if (AuditPageFailed::validateVersion($this->version))  {
            return $this->version;
        }
        throw new Exception('never get to getVersion AuditPageFailed::version');
    }

    /**
     * @return string
     */
    public static function sampleVersion(): string {
        return 'AuditPageFailed::version::34'; /*34:version*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditPageFailed::validatePayload($this->payload)
        || AuditPageFailed::validateTimestamp($this->timestamp)
        || AuditPageFailed::validateType($this->type)
        || AuditPageFailed::validateVersion($this->version);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'payload'} = $this->toPayload();
        $out->{'timestamp'} = $this->toTimestamp();
        $out->{'type'} = $this->toType();
        $out->{'version'} = $this->toVersion();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditPageFailed
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditPageFailed {
        return new AuditPageFailed(
         AuditPageFailed::fromPayload($obj->{'payload'})
        ,AuditPageFailed::fromTimestamp($obj->{'timestamp'})
        ,AuditPageFailed::fromType($obj->{'type'})
        ,AuditPageFailed::fromVersion($obj->{'version'})
        );
    }

    /**
     * @return AuditPageFailed
     */
    public static function sample(): AuditPageFailed {
        return new AuditPageFailed(
         AuditPageFailed::samplePayload()
        ,AuditPageFailed::sampleTimestamp()
        ,AuditPageFailed::sampleType()
        ,AuditPageFailed::sampleVersion()
        );
    }
}

// This is an autogenerated file:AuditPageFailedPayload

class AuditPageFailedPayload {
    private int $attemptsCount; // json:attemptsCount Required
    private string $auditId; // json:auditId Required
    private string $errorMessage; // json:errorMessage Required
    private string $pageUrl; // json:pageUrl Required

    /**
     * @param int $attemptsCount
     * @param string $auditId
     * @param string $errorMessage
     * @param string $pageUrl
     */
    public function __construct(int $attemptsCount, string $auditId, string $errorMessage, string $pageUrl) {
        $this->attemptsCount = $attemptsCount;
        $this->auditId = $auditId;
        $this->errorMessage = $errorMessage;
        $this->pageUrl = $pageUrl;
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromAttemptsCount(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toAttemptsCount(): int {
        if (AuditPageFailedPayload::validateAttemptsCount($this->attemptsCount))  {
            return $this->attemptsCount; /*int*/
        }
        throw new Exception('never get to this AuditPageFailedPayload::attemptsCount');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateAttemptsCount(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditPageFailedPayload::attemptsCount");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getAttemptsCount(): int {
        if (AuditPageFailedPayload::validateAttemptsCount($this->attemptsCount))  {
            return $this->attemptsCount;
        }
        throw new Exception('never get to getAttemptsCount AuditPageFailedPayload::attemptsCount');
    }

    /**
     * @return int
     */
    public static function sampleAttemptsCount(): int {
        return 31; /*31:attemptsCount*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromAuditId(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toAuditId(): string {
        if (AuditPageFailedPayload::validateAuditId($this->auditId))  {
            return $this->auditId; /*string*/
        }
        throw new Exception('never get to this AuditPageFailedPayload::auditId');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateAuditId(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditPageFailedPayload::auditId");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getAuditId(): string {
        if (AuditPageFailedPayload::validateAuditId($this->auditId))  {
            return $this->auditId;
        }
        throw new Exception('never get to getAuditId AuditPageFailedPayload::auditId');
    }

    /**
     * @return string
     */
    public static function sampleAuditId(): string {
        return 'AuditPageFailedPayload::auditId::32'; /*32:auditId*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromErrorMessage(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toErrorMessage(): string {
        if (AuditPageFailedPayload::validateErrorMessage($this->errorMessage))  {
            return $this->errorMessage; /*string*/
        }
        throw new Exception('never get to this AuditPageFailedPayload::errorMessage');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateErrorMessage(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditPageFailedPayload::errorMessage");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getErrorMessage(): string {
        if (AuditPageFailedPayload::validateErrorMessage($this->errorMessage))  {
            return $this->errorMessage;
        }
        throw new Exception('never get to getErrorMessage AuditPageFailedPayload::errorMessage');
    }

    /**
     * @return string
     */
    public static function sampleErrorMessage(): string {
        return 'AuditPageFailedPayload::errorMessage::33'; /*33:errorMessage*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromPageUrl(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toPageUrl(): string {
        if (AuditPageFailedPayload::validatePageUrl($this->pageUrl))  {
            return $this->pageUrl; /*string*/
        }
        throw new Exception('never get to this AuditPageFailedPayload::pageUrl');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validatePageUrl(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditPageFailedPayload::pageUrl");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getPageUrl(): string {
        if (AuditPageFailedPayload::validatePageUrl($this->pageUrl))  {
            return $this->pageUrl;
        }
        throw new Exception('never get to getPageUrl AuditPageFailedPayload::pageUrl');
    }

    /**
     * @return string
     */
    public static function samplePageUrl(): string {
        return 'AuditPageFailedPayload::pageUrl::34'; /*34:pageUrl*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditPageFailedPayload::validateAttemptsCount($this->attemptsCount)
        || AuditPageFailedPayload::validateAuditId($this->auditId)
        || AuditPageFailedPayload::validateErrorMessage($this->errorMessage)
        || AuditPageFailedPayload::validatePageUrl($this->pageUrl);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'attemptsCount'} = $this->toAttemptsCount();
        $out->{'auditId'} = $this->toAuditId();
        $out->{'errorMessage'} = $this->toErrorMessage();
        $out->{'pageUrl'} = $this->toPageUrl();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditPageFailedPayload
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditPageFailedPayload {
        return new AuditPageFailedPayload(
         AuditPageFailedPayload::fromAttemptsCount($obj->{'attemptsCount'})
        ,AuditPageFailedPayload::fromAuditId($obj->{'auditId'})
        ,AuditPageFailedPayload::fromErrorMessage($obj->{'errorMessage'})
        ,AuditPageFailedPayload::fromPageUrl($obj->{'pageUrl'})
        );
    }

    /**
     * @return AuditPageFailedPayload
     */
    public static function sample(): AuditPageFailedPayload {
        return new AuditPageFailedPayload(
         AuditPageFailedPayload::sampleAttemptsCount()
        ,AuditPageFailedPayload::sampleAuditId()
        ,AuditPageFailedPayload::sampleErrorMessage()
        ,AuditPageFailedPayload::samplePageUrl()
        );
    }
}

// This is an autogenerated file:AuditPageFailedType

class AuditPageFailedType {
    public static AuditPageFailedType $AUDIT_PAGE_FAILED;
    public static function init() {
        AuditPageFailedType::$AUDIT_PAGE_FAILED = new AuditPageFailedType('audit.page.failed');
    }
    private string $enum;
    public function __construct(string $enum) {
        $this->enum = $enum;
    }

    /**
     * @param AuditPageFailedType
     * @return string
     * @throws Exception
     */
    public static function to(AuditPageFailedType $obj): string {
        switch ($obj->enum) {
            case AuditPageFailedType::$AUDIT_PAGE_FAILED->enum: return 'audit.page.failed';
        }
        throw new Exception('the give value is not an enum-value.');
    }

    /**
     * @param mixed
     * @return AuditPageFailedType
     * @throws Exception
     */
    public static function from($obj): AuditPageFailedType {
        switch ($obj) {
            case 'audit.page.failed': return AuditPageFailedType::$AUDIT_PAGE_FAILED;
        }
        throw new Exception("Cannot deserialize AuditPageFailedType");
    }

    /**
     * @return AuditPageFailedType
     */
    public static function sample(): AuditPageFailedType {
        return AuditPageFailedType::$AUDIT_PAGE_FAILED;
    }
}
AuditPageFailedType::init();
