<?php

namespace EqualSite\Events\Value;

use Exception;
use stdClass;

// This is an autogenerated file:AuditQueued

class AuditQueued {
    private AuditQueuedPayload $payload; // json:payload Required
    private int $timestamp; // json:timestamp Required
    private AuditQueuedType $type; // json:type Required
    private string $version; // json:version Required

    /**
     * @param AuditQueuedPayload $payload
     * @param int $timestamp
     * @param AuditQueuedType $type
     * @param string $version
     */
    public function __construct(AuditQueuedPayload $payload, int $timestamp, AuditQueuedType $type, string $version) {
        $this->payload = $payload;
        $this->timestamp = $timestamp;
        $this->type = $type;
        $this->version = $version;
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return AuditQueuedPayload
     */
    public static function fromPayload(stdClass $value): AuditQueuedPayload {
        return AuditQueuedPayload::from($value); /*class*/
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toPayload(): stdClass {
        if (AuditQueued::validatePayload($this->payload))  {
            return $this->payload->to(); /*class*/
        }
        throw new Exception('never get to this AuditQueued::payload');
    }

    /**
     * @param AuditQueuedPayload
     * @return bool
     * @throws Exception
     */
    public static function validatePayload(AuditQueuedPayload $value): bool {
        $value->validate();
        return true;
    }

    /**
     * @throws Exception
     * @return AuditQueuedPayload
     */
    public function getPayload(): AuditQueuedPayload {
        if (AuditQueued::validatePayload($this->payload))  {
            return $this->payload;
        }
        throw new Exception('never get to getPayload AuditQueued::payload');
    }

    /**
     * @return AuditQueuedPayload
     */
    public static function samplePayload(): AuditQueuedPayload {
        return AuditQueuedPayload::sample(); /*31:payload*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromTimestamp(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toTimestamp(): int {
        if (AuditQueued::validateTimestamp($this->timestamp))  {
            return $this->timestamp; /*int*/
        }
        throw new Exception('never get to this AuditQueued::timestamp');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateTimestamp(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditQueued::timestamp");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getTimestamp(): int {
        if (AuditQueued::validateTimestamp($this->timestamp))  {
            return $this->timestamp;
        }
        throw new Exception('never get to getTimestamp AuditQueued::timestamp');
    }

    /**
     * @return int
     */
    public static function sampleTimestamp(): int {
        return 32; /*32:timestamp*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return AuditQueuedType
     */
    public static function fromType(string $value): AuditQueuedType {
        return AuditQueuedType::from($value); /*enum*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toType(): string {
        if (AuditQueued::validateType($this->type))  {
            return AuditQueuedType::to($this->type); /*enum*/
        }
        throw new Exception('never get to this AuditQueued::type');
    }

    /**
     * @param AuditQueuedType
     * @return bool
     * @throws Exception
     */
    public static function validateType(AuditQueuedType $value): bool {
        AuditQueuedType::to($value);
        return true;
    }

    /**
     * @throws Exception
     * @return AuditQueuedType
     */
    public function getType(): AuditQueuedType {
        if (AuditQueued::validateType($this->type))  {
            return $this->type;
        }
        throw new Exception('never get to getType AuditQueued::type');
    }

    /**
     * @return AuditQueuedType
     */
    public static function sampleType(): AuditQueuedType {
        return AuditQueuedType::sample(); /*enum*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromVersion(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toVersion(): string {
        if (AuditQueued::validateVersion($this->version))  {
            return $this->version; /*string*/
        }
        throw new Exception('never get to this AuditQueued::version');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateVersion(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditQueued::version");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getVersion(): string {
        if (AuditQueued::validateVersion($this->version))  {
            return $this->version;
        }
        throw new Exception('never get to getVersion AuditQueued::version');
    }

    /**
     * @return string
     */
    public static function sampleVersion(): string {
        return 'AuditQueued::version::34'; /*34:version*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditQueued::validatePayload($this->payload)
        || AuditQueued::validateTimestamp($this->timestamp)
        || AuditQueued::validateType($this->type)
        || AuditQueued::validateVersion($this->version);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'payload'} = $this->toPayload();
        $out->{'timestamp'} = $this->toTimestamp();
        $out->{'type'} = $this->toType();
        $out->{'version'} = $this->toVersion();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditQueued
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditQueued {
        return new AuditQueued(
         AuditQueued::fromPayload($obj->{'payload'})
        ,AuditQueued::fromTimestamp($obj->{'timestamp'})
        ,AuditQueued::fromType($obj->{'type'})
        ,AuditQueued::fromVersion($obj->{'version'})
        );
    }

    /**
     * @return AuditQueued
     */
    public static function sample(): AuditQueued {
        return new AuditQueued(
         AuditQueued::samplePayload()
        ,AuditQueued::sampleTimestamp()
        ,AuditQueued::sampleType()
        ,AuditQueued::sampleVersion()
        );
    }
}

// This is an autogenerated file:AuditQueuedPayload

class AuditQueuedPayload {
    private int $ahead; // json:ahead Required
    private string $auditId; // json:auditId Required
    private int $position; // json:position Required
    private int $waiting; // json:waiting Required

    /**
     * @param int $ahead
     * @param string $auditId
     * @param int $position
     * @param int $waiting
     */
    public function __construct(int $ahead, string $auditId, int $position, int $waiting) {
        $this->ahead = $ahead;
        $this->auditId = $auditId;
        $this->position = $position;
        $this->waiting = $waiting;
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromAhead(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toAhead(): int {
        if (AuditQueuedPayload::validateAhead($this->ahead))  {
            return $this->ahead; /*int*/
        }
        throw new Exception('never get to this AuditQueuedPayload::ahead');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateAhead(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditQueuedPayload::ahead");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getAhead(): int {
        if (AuditQueuedPayload::validateAhead($this->ahead))  {
            return $this->ahead;
        }
        throw new Exception('never get to getAhead AuditQueuedPayload::ahead');
    }

    /**
     * @return int
     */
    public static function sampleAhead(): int {
        return 31; /*31:ahead*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromAuditId(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toAuditId(): string {
        if (AuditQueuedPayload::validateAuditId($this->auditId))  {
            return $this->auditId; /*string*/
        }
        throw new Exception('never get to this AuditQueuedPayload::auditId');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateAuditId(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditQueuedPayload::auditId");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getAuditId(): string {
        if (AuditQueuedPayload::validateAuditId($this->auditId))  {
            return $this->auditId;
        }
        throw new Exception('never get to getAuditId AuditQueuedPayload::auditId');
    }

    /**
     * @return string
     */
    public static function sampleAuditId(): string {
        return 'AuditQueuedPayload::auditId::32'; /*32:auditId*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromPosition(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toPosition(): int {
        if (AuditQueuedPayload::validatePosition($this->position))  {
            return $this->position; /*int*/
        }
        throw new Exception('never get to this AuditQueuedPayload::position');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validatePosition(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditQueuedPayload::position");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getPosition(): int {
        if (AuditQueuedPayload::validatePosition($this->position))  {
            return $this->position;
        }
        throw new Exception('never get to getPosition AuditQueuedPayload::position');
    }

    /**
     * @return int
     */
    public static function samplePosition(): int {
        return 33; /*33:position*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromWaiting(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toWaiting(): int {
        if (AuditQueuedPayload::validateWaiting($this->waiting))  {
            return $this->waiting; /*int*/
        }
        throw new Exception('never get to this AuditQueuedPayload::waiting');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateWaiting(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditQueuedPayload::waiting");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getWaiting(): int {
        if (AuditQueuedPayload::validateWaiting($this->waiting))  {
            return $this->waiting;
        }
        throw new Exception('never get to getWaiting AuditQueuedPayload::waiting');
    }

    /**
     * @return int
     */
    public static function sampleWaiting(): int {
        return 34; /*34:waiting*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditQueuedPayload::validateAhead($this->ahead)
        || AuditQueuedPayload::validateAuditId($this->auditId)
        || AuditQueuedPayload::validatePosition($this->position)
        || AuditQueuedPayload::validateWaiting($this->waiting);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'ahead'} = $this->toAhead();
        $out->{'auditId'} = $this->toAuditId();
        $out->{'position'} = $this->toPosition();
        $out->{'waiting'} = $this->toWaiting();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditQueuedPayload
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditQueuedPayload {
        return new AuditQueuedPayload(
         AuditQueuedPayload::fromAhead($obj->{'ahead'})
        ,AuditQueuedPayload::fromAuditId($obj->{'auditId'})
        ,AuditQueuedPayload::fromPosition($obj->{'position'})
        ,AuditQueuedPayload::fromWaiting($obj->{'waiting'})
        );
    }

    /**
     * @return AuditQueuedPayload
     */
    public static function sample(): AuditQueuedPayload {
        return new AuditQueuedPayload(
         AuditQueuedPayload::sampleAhead()
        ,AuditQueuedPayload::sampleAuditId()
        ,AuditQueuedPayload::samplePosition()
        ,AuditQueuedPayload::sampleWaiting()
        );
    }
}

// This is an autogenerated file:AuditQueuedType

class AuditQueuedType {
    public static AuditQueuedType $AUDIT_QUEUED;
    public static function init() {
        AuditQueuedType::$AUDIT_QUEUED = new AuditQueuedType('audit.queued');
    }
    private string $enum;
    public function __construct(string $enum) {
        $this->enum = $enum;
    }

    /**
     * @param AuditQueuedType
     * @return string
     * @throws Exception
     */
    public static function to(AuditQueuedType $obj): string {
        switch ($obj->enum) {
            case AuditQueuedType::$AUDIT_QUEUED->enum: return 'audit.queued';
        }
        throw new Exception('the give value is not an enum-value.');
    }

    /**
     * @param mixed
     * @return AuditQueuedType
     * @throws Exception
     */
    public static function from($obj): AuditQueuedType {
        switch ($obj) {
            case 'audit.queued': return AuditQueuedType::$AUDIT_QUEUED;
        }
        throw new Exception("Cannot deserialize AuditQueuedType");
    }

    /**
     * @return AuditQueuedType
     */
    public static function sample(): AuditQueuedType {
        return AuditQueuedType::$AUDIT_QUEUED;
    }
}
AuditQueuedType::init();
