<?php

namespace EqualSite\Events\Value;

use Exception;
use stdClass;

// This is an autogenerated file:AuditPageSkipped

class AuditPageSkipped {
    private AuditPageSkippedPayload $payload; // json:payload Required
    private int $timestamp; // json:timestamp Required
    private AuditPageSkippedType $type; // json:type Required
    private string $version; // json:version Required

    /**
     * @param AuditPageSkippedPayload $payload
     * @param int $timestamp
     * @param AuditPageSkippedType $type
     * @param string $version
     */
    public function __construct(AuditPageSkippedPayload $payload, int $timestamp, AuditPageSkippedType $type, string $version) {
        $this->payload = $payload;
        $this->timestamp = $timestamp;
        $this->type = $type;
        $this->version = $version;
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return AuditPageSkippedPayload
     */
    public static function fromPayload(stdClass $value): AuditPageSkippedPayload {
        return AuditPageSkippedPayload::from($value); /*class*/
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toPayload(): stdClass {
        if (AuditPageSkipped::validatePayload($this->payload))  {
            return $this->payload->to(); /*class*/
        }
        throw new Exception('never get to this AuditPageSkipped::payload');
    }

    /**
     * @param AuditPageSkippedPayload
     * @return bool
     * @throws Exception
     */
    public static function validatePayload(AuditPageSkippedPayload $value): bool {
        $value->validate();
        return true;
    }

    /**
     * @throws Exception
     * @return AuditPageSkippedPayload
     */
    public function getPayload(): AuditPageSkippedPayload {
        if (AuditPageSkipped::validatePayload($this->payload))  {
            return $this->payload;
        }
        throw new Exception('never get to getPayload AuditPageSkipped::payload');
    }

    /**
     * @return AuditPageSkippedPayload
     */
    public static function samplePayload(): AuditPageSkippedPayload {
        return AuditPageSkippedPayload::sample(); /*31:payload*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromTimestamp(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toTimestamp(): int {
        if (AuditPageSkipped::validateTimestamp($this->timestamp))  {
            return $this->timestamp; /*int*/
        }
        throw new Exception('never get to this AuditPageSkipped::timestamp');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateTimestamp(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:AuditPageSkipped::timestamp");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getTimestamp(): int {
        if (AuditPageSkipped::validateTimestamp($this->timestamp))  {
            return $this->timestamp;
        }
        throw new Exception('never get to getTimestamp AuditPageSkipped::timestamp');
    }

    /**
     * @return int
     */
    public static function sampleTimestamp(): int {
        return 32; /*32:timestamp*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return AuditPageSkippedType
     */
    public static function fromType(string $value): AuditPageSkippedType {
        return AuditPageSkippedType::from($value); /*enum*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toType(): string {
        if (AuditPageSkipped::validateType($this->type))  {
            return AuditPageSkippedType::to($this->type); /*enum*/
        }
        throw new Exception('never get to this AuditPageSkipped::type');
    }

    /**
     * @param AuditPageSkippedType
     * @return bool
     * @throws Exception
     */
    public static function validateType(AuditPageSkippedType $value): bool {
        AuditPageSkippedType::to($value);
        return true;
    }

    /**
     * @throws Exception
     * @return AuditPageSkippedType
     */
    public function getType(): AuditPageSkippedType {
        if (AuditPageSkipped::validateType($this->type))  {
            return $this->type;
        }
        throw new Exception('never get to getType AuditPageSkipped::type');
    }

    /**
     * @return AuditPageSkippedType
     */
    public static function sampleType(): AuditPageSkippedType {
        return AuditPageSkippedType::sample(); /*enum*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromVersion(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toVersion(): string {
        if (AuditPageSkipped::validateVersion($this->version))  {
            return $this->version; /*string*/
        }
        throw new Exception('never get to this AuditPageSkipped::version');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateVersion(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditPageSkipped::version");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getVersion(): string {
        if (AuditPageSkipped::validateVersion($this->version))  {
            return $this->version;
        }
        throw new Exception('never get to getVersion AuditPageSkipped::version');
    }

    /**
     * @return string
     */
    public static function sampleVersion(): string {
        return 'AuditPageSkipped::version::34'; /*34:version*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditPageSkipped::validatePayload($this->payload)
        || AuditPageSkipped::validateTimestamp($this->timestamp)
        || AuditPageSkipped::validateType($this->type)
        || AuditPageSkipped::validateVersion($this->version);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'payload'} = $this->toPayload();
        $out->{'timestamp'} = $this->toTimestamp();
        $out->{'type'} = $this->toType();
        $out->{'version'} = $this->toVersion();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditPageSkipped
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditPageSkipped {
        return new AuditPageSkipped(
         AuditPageSkipped::fromPayload($obj->{'payload'})
        ,AuditPageSkipped::fromTimestamp($obj->{'timestamp'})
        ,AuditPageSkipped::fromType($obj->{'type'})
        ,AuditPageSkipped::fromVersion($obj->{'version'})
        );
    }

    /**
     * @return AuditPageSkipped
     */
    public static function sample(): AuditPageSkipped {
        return new AuditPageSkipped(
         AuditPageSkipped::samplePayload()
        ,AuditPageSkipped::sampleTimestamp()
        ,AuditPageSkipped::sampleType()
        ,AuditPageSkipped::sampleVersion()
        );
    }
}

// This is an autogenerated file:AuditPageSkippedPayload

class AuditPageSkippedPayload {
    private string $auditId; // json:auditId Required
    private string $pageUrl; // json:pageUrl Required
    private string $reason; // json:reason Required

    /**
     * @param string $auditId
     * @param string $pageUrl
     * @param string $reason
     */
    public function __construct(string $auditId, string $pageUrl, string $reason) {
        $this->auditId = $auditId;
        $this->pageUrl = $pageUrl;
        $this->reason = $reason;
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromAuditId(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toAuditId(): string {
        if (AuditPageSkippedPayload::validateAuditId($this->auditId))  {
            return $this->auditId; /*string*/
        }
        throw new Exception('never get to this AuditPageSkippedPayload::auditId');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateAuditId(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditPageSkippedPayload::auditId");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getAuditId(): string {
        if (AuditPageSkippedPayload::validateAuditId($this->auditId))  {
            return $this->auditId;
        }
        throw new Exception('never get to getAuditId AuditPageSkippedPayload::auditId');
    }

    /**
     * @return string
     */
    public static function sampleAuditId(): string {
        return 'AuditPageSkippedPayload::auditId::31'; /*31:auditId*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromPageUrl(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toPageUrl(): string {
        if (AuditPageSkippedPayload::validatePageUrl($this->pageUrl))  {
            return $this->pageUrl; /*string*/
        }
        throw new Exception('never get to this AuditPageSkippedPayload::pageUrl');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validatePageUrl(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditPageSkippedPayload::pageUrl");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getPageUrl(): string {
        if (AuditPageSkippedPayload::validatePageUrl($this->pageUrl))  {
            return $this->pageUrl;
        }
        throw new Exception('never get to getPageUrl AuditPageSkippedPayload::pageUrl');
    }

    /**
     * @return string
     */
    public static function samplePageUrl(): string {
        return 'AuditPageSkippedPayload::pageUrl::32'; /*32:pageUrl*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromReason(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toReason(): string {
        if (AuditPageSkippedPayload::validateReason($this->reason))  {
            return $this->reason; /*string*/
        }
        throw new Exception('never get to this AuditPageSkippedPayload::reason');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateReason(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:AuditPageSkippedPayload::reason");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getReason(): string {
        if (AuditPageSkippedPayload::validateReason($this->reason))  {
            return $this->reason;
        }
        throw new Exception('never get to getReason AuditPageSkippedPayload::reason');
    }

    /**
     * @return string
     */
    public static function sampleReason(): string {
        return 'AuditPageSkippedPayload::reason::33'; /*33:reason*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return AuditPageSkippedPayload::validateAuditId($this->auditId)
        || AuditPageSkippedPayload::validatePageUrl($this->pageUrl)
        || AuditPageSkippedPayload::validateReason($this->reason);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'auditId'} = $this->toAuditId();
        $out->{'pageUrl'} = $this->toPageUrl();
        $out->{'reason'} = $this->toReason();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return AuditPageSkippedPayload
     * @throws Exception
     */
    public static function from(stdClass $obj): AuditPageSkippedPayload {
        return new AuditPageSkippedPayload(
         AuditPageSkippedPayload::fromAuditId($obj->{'auditId'})
        ,AuditPageSkippedPayload::fromPageUrl($obj->{'pageUrl'})
        ,AuditPageSkippedPayload::fromReason($obj->{'reason'})
        );
    }

    /**
     * @return AuditPageSkippedPayload
     */
    public static function sample(): AuditPageSkippedPayload {
        return new AuditPageSkippedPayload(
         AuditPageSkippedPayload::sampleAuditId()
        ,AuditPageSkippedPayload::samplePageUrl()
        ,AuditPageSkippedPayload::sampleReason()
        );
    }
}

// This is an autogenerated file:AuditPageSkippedType

class AuditPageSkippedType {
    public static AuditPageSkippedType $AUDIT_PAGE_SKIPPED;
    public static function init() {
        AuditPageSkippedType::$AUDIT_PAGE_SKIPPED = new AuditPageSkippedType('audit.page.skipped');
    }
    private string $enum;
    public function __construct(string $enum) {
        $this->enum = $enum;
    }

    /**
     * @param AuditPageSkippedType
     * @return string
     * @throws Exception
     */
    public static function to(AuditPageSkippedType $obj): string {
        switch ($obj->enum) {
            case AuditPageSkippedType::$AUDIT_PAGE_SKIPPED->enum: return 'audit.page.skipped';
        }
        throw new Exception('the give value is not an enum-value.');
    }

    /**
     * @param mixed
     * @return AuditPageSkippedType
     * @throws Exception
     */
    public static function from($obj): AuditPageSkippedType {
        switch ($obj) {
            case 'audit.page.skipped': return AuditPageSkippedType::$AUDIT_PAGE_SKIPPED;
        }
        throw new Exception("Cannot deserialize AuditPageSkippedType");
    }

    /**
     * @return AuditPageSkippedType
     */
    public static function sample(): AuditPageSkippedType {
        return AuditPageSkippedType::$AUDIT_PAGE_SKIPPED;
    }
}
AuditPageSkippedType::init();
