<?php

namespace EqualSite\Events\Value;

use Exception;
use stdClass;

// This is an autogenerated file:CrawlerTelemetry

class CrawlerTelemetry {
    private CrawlerTelemetryPayload $payload; // json:payload Required
    private int $timestamp; // json:timestamp Required
    private CrawlerTelemetryType $type; // json:type Required
    private string $version; // json:version Required

    /**
     * @param CrawlerTelemetryPayload $payload
     * @param int $timestamp
     * @param CrawlerTelemetryType $type
     * @param string $version
     */
    public function __construct(CrawlerTelemetryPayload $payload, int $timestamp, CrawlerTelemetryType $type, string $version) {
        $this->payload = $payload;
        $this->timestamp = $timestamp;
        $this->type = $type;
        $this->version = $version;
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return CrawlerTelemetryPayload
     */
    public static function fromPayload(stdClass $value): CrawlerTelemetryPayload {
        return CrawlerTelemetryPayload::from($value); /*class*/
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toPayload(): stdClass {
        if (CrawlerTelemetry::validatePayload($this->payload))  {
            return $this->payload->to(); /*class*/
        }
        throw new Exception('never get to this CrawlerTelemetry::payload');
    }

    /**
     * @param CrawlerTelemetryPayload
     * @return bool
     * @throws Exception
     */
    public static function validatePayload(CrawlerTelemetryPayload $value): bool {
        $value->validate();
        return true;
    }

    /**
     * @throws Exception
     * @return CrawlerTelemetryPayload
     */
    public function getPayload(): CrawlerTelemetryPayload {
        if (CrawlerTelemetry::validatePayload($this->payload))  {
            return $this->payload;
        }
        throw new Exception('never get to getPayload CrawlerTelemetry::payload');
    }

    /**
     * @return CrawlerTelemetryPayload
     */
    public static function samplePayload(): CrawlerTelemetryPayload {
        return CrawlerTelemetryPayload::sample(); /*31:payload*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromTimestamp(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toTimestamp(): int {
        if (CrawlerTelemetry::validateTimestamp($this->timestamp))  {
            return $this->timestamp; /*int*/
        }
        throw new Exception('never get to this CrawlerTelemetry::timestamp');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateTimestamp(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:CrawlerTelemetry::timestamp");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getTimestamp(): int {
        if (CrawlerTelemetry::validateTimestamp($this->timestamp))  {
            return $this->timestamp;
        }
        throw new Exception('never get to getTimestamp CrawlerTelemetry::timestamp');
    }

    /**
     * @return int
     */
    public static function sampleTimestamp(): int {
        return 32; /*32:timestamp*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return CrawlerTelemetryType
     */
    public static function fromType(string $value): CrawlerTelemetryType {
        return CrawlerTelemetryType::from($value); /*enum*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toType(): string {
        if (CrawlerTelemetry::validateType($this->type))  {
            return CrawlerTelemetryType::to($this->type); /*enum*/
        }
        throw new Exception('never get to this CrawlerTelemetry::type');
    }

    /**
     * @param CrawlerTelemetryType
     * @return bool
     * @throws Exception
     */
    public static function validateType(CrawlerTelemetryType $value): bool {
        CrawlerTelemetryType::to($value);
        return true;
    }

    /**
     * @throws Exception
     * @return CrawlerTelemetryType
     */
    public function getType(): CrawlerTelemetryType {
        if (CrawlerTelemetry::validateType($this->type))  {
            return $this->type;
        }
        throw new Exception('never get to getType CrawlerTelemetry::type');
    }

    /**
     * @return CrawlerTelemetryType
     */
    public static function sampleType(): CrawlerTelemetryType {
        return CrawlerTelemetryType::sample(); /*enum*/
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromVersion(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toVersion(): string {
        if (CrawlerTelemetry::validateVersion($this->version))  {
            return $this->version; /*string*/
        }
        throw new Exception('never get to this CrawlerTelemetry::version');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateVersion(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:CrawlerTelemetry::version");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return string
     */
    public function getVersion(): string {
        if (CrawlerTelemetry::validateVersion($this->version))  {
            return $this->version;
        }
        throw new Exception('never get to getVersion CrawlerTelemetry::version');
    }

    /**
     * @return string
     */
    public static function sampleVersion(): string {
        return 'CrawlerTelemetry::version::34'; /*34:version*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return CrawlerTelemetry::validatePayload($this->payload)
        || CrawlerTelemetry::validateTimestamp($this->timestamp)
        || CrawlerTelemetry::validateType($this->type)
        || CrawlerTelemetry::validateVersion($this->version);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'payload'} = $this->toPayload();
        $out->{'timestamp'} = $this->toTimestamp();
        $out->{'type'} = $this->toType();
        $out->{'version'} = $this->toVersion();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return CrawlerTelemetry
     * @throws Exception
     */
    public static function from(stdClass $obj): CrawlerTelemetry {
        return new CrawlerTelemetry(
         CrawlerTelemetry::fromPayload($obj->{'payload'})
        ,CrawlerTelemetry::fromTimestamp($obj->{'timestamp'})
        ,CrawlerTelemetry::fromType($obj->{'type'})
        ,CrawlerTelemetry::fromVersion($obj->{'version'})
        );
    }

    /**
     * @return CrawlerTelemetry
     */
    public static function sample(): CrawlerTelemetry {
        return new CrawlerTelemetry(
         CrawlerTelemetry::samplePayload()
        ,CrawlerTelemetry::sampleTimestamp()
        ,CrawlerTelemetry::sampleType()
        ,CrawlerTelemetry::sampleVersion()
        );
    }
}

// This is an autogenerated file:CrawlerTelemetryPayload

class CrawlerTelemetryPayload {
    private CrawlerTelemetryCrawlers $crawlers; // json:crawlers Required
    private CrawlerTelemetryProcess $process; // json:process Required
    private CrawlerTelemetryQueue $queue; // json:queue Required
    private CrawlerTelemetrySystem $system; // json:system Required

    /**
     * @param CrawlerTelemetryCrawlers $crawlers
     * @param CrawlerTelemetryProcess $process
     * @param CrawlerTelemetryQueue $queue
     * @param CrawlerTelemetrySystem $system
     */
    public function __construct(CrawlerTelemetryCrawlers $crawlers, CrawlerTelemetryProcess $process, CrawlerTelemetryQueue $queue, CrawlerTelemetrySystem $system) {
        $this->crawlers = $crawlers;
        $this->process = $process;
        $this->queue = $queue;
        $this->system = $system;
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return CrawlerTelemetryCrawlers
     */
    public static function fromCrawlers(stdClass $value): CrawlerTelemetryCrawlers {
        return CrawlerTelemetryCrawlers::from($value); /*class*/
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toCrawlers(): stdClass {
        if (CrawlerTelemetryPayload::validateCrawlers($this->crawlers))  {
            return $this->crawlers->to(); /*class*/
        }
        throw new Exception('never get to this CrawlerTelemetryPayload::crawlers');
    }

    /**
     * @param CrawlerTelemetryCrawlers
     * @return bool
     * @throws Exception
     */
    public static function validateCrawlers(CrawlerTelemetryCrawlers $value): bool {
        $value->validate();
        return true;
    }

    /**
     * @throws Exception
     * @return CrawlerTelemetryCrawlers
     */
    public function getCrawlers(): CrawlerTelemetryCrawlers {
        if (CrawlerTelemetryPayload::validateCrawlers($this->crawlers))  {
            return $this->crawlers;
        }
        throw new Exception('never get to getCrawlers CrawlerTelemetryPayload::crawlers');
    }

    /**
     * @return CrawlerTelemetryCrawlers
     */
    public static function sampleCrawlers(): CrawlerTelemetryCrawlers {
        return CrawlerTelemetryCrawlers::sample(); /*31:crawlers*/
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return CrawlerTelemetryProcess
     */
    public static function fromProcess(stdClass $value): CrawlerTelemetryProcess {
        return CrawlerTelemetryProcess::from($value); /*class*/
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toProcess(): stdClass {
        if (CrawlerTelemetryPayload::validateProcess($this->process))  {
            return $this->process->to(); /*class*/
        }
        throw new Exception('never get to this CrawlerTelemetryPayload::process');
    }

    /**
     * @param CrawlerTelemetryProcess
     * @return bool
     * @throws Exception
     */
    public static function validateProcess(CrawlerTelemetryProcess $value): bool {
        $value->validate();
        return true;
    }

    /**
     * @throws Exception
     * @return CrawlerTelemetryProcess
     */
    public function getProcess(): CrawlerTelemetryProcess {
        if (CrawlerTelemetryPayload::validateProcess($this->process))  {
            return $this->process;
        }
        throw new Exception('never get to getProcess CrawlerTelemetryPayload::process');
    }

    /**
     * @return CrawlerTelemetryProcess
     */
    public static function sampleProcess(): CrawlerTelemetryProcess {
        return CrawlerTelemetryProcess::sample(); /*32:process*/
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return CrawlerTelemetryQueue
     */
    public static function fromQueue(stdClass $value): CrawlerTelemetryQueue {
        return CrawlerTelemetryQueue::from($value); /*class*/
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toQueue(): stdClass {
        if (CrawlerTelemetryPayload::validateQueue($this->queue))  {
            return $this->queue->to(); /*class*/
        }
        throw new Exception('never get to this CrawlerTelemetryPayload::queue');
    }

    /**
     * @param CrawlerTelemetryQueue
     * @return bool
     * @throws Exception
     */
    public static function validateQueue(CrawlerTelemetryQueue $value): bool {
        $value->validate();
        return true;
    }

    /**
     * @throws Exception
     * @return CrawlerTelemetryQueue
     */
    public function getQueue(): CrawlerTelemetryQueue {
        if (CrawlerTelemetryPayload::validateQueue($this->queue))  {
            return $this->queue;
        }
        throw new Exception('never get to getQueue CrawlerTelemetryPayload::queue');
    }

    /**
     * @return CrawlerTelemetryQueue
     */
    public static function sampleQueue(): CrawlerTelemetryQueue {
        return CrawlerTelemetryQueue::sample(); /*33:queue*/
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return CrawlerTelemetrySystem
     */
    public static function fromSystem(stdClass $value): CrawlerTelemetrySystem {
        return CrawlerTelemetrySystem::from($value); /*class*/
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toSystem(): stdClass {
        if (CrawlerTelemetryPayload::validateSystem($this->system))  {
            return $this->system->to(); /*class*/
        }
        throw new Exception('never get to this CrawlerTelemetryPayload::system');
    }

    /**
     * @param CrawlerTelemetrySystem
     * @return bool
     * @throws Exception
     */
    public static function validateSystem(CrawlerTelemetrySystem $value): bool {
        $value->validate();
        return true;
    }

    /**
     * @throws Exception
     * @return CrawlerTelemetrySystem
     */
    public function getSystem(): CrawlerTelemetrySystem {
        if (CrawlerTelemetryPayload::validateSystem($this->system))  {
            return $this->system;
        }
        throw new Exception('never get to getSystem CrawlerTelemetryPayload::system');
    }

    /**
     * @return CrawlerTelemetrySystem
     */
    public static function sampleSystem(): CrawlerTelemetrySystem {
        return CrawlerTelemetrySystem::sample(); /*34:system*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return CrawlerTelemetryPayload::validateCrawlers($this->crawlers)
        || CrawlerTelemetryPayload::validateProcess($this->process)
        || CrawlerTelemetryPayload::validateQueue($this->queue)
        || CrawlerTelemetryPayload::validateSystem($this->system);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'crawlers'} = $this->toCrawlers();
        $out->{'process'} = $this->toProcess();
        $out->{'queue'} = $this->toQueue();
        $out->{'system'} = $this->toSystem();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return CrawlerTelemetryPayload
     * @throws Exception
     */
    public static function from(stdClass $obj): CrawlerTelemetryPayload {
        return new CrawlerTelemetryPayload(
         CrawlerTelemetryPayload::fromCrawlers($obj->{'crawlers'})
        ,CrawlerTelemetryPayload::fromProcess($obj->{'process'})
        ,CrawlerTelemetryPayload::fromQueue($obj->{'queue'})
        ,CrawlerTelemetryPayload::fromSystem($obj->{'system'})
        );
    }

    /**
     * @return CrawlerTelemetryPayload
     */
    public static function sample(): CrawlerTelemetryPayload {
        return new CrawlerTelemetryPayload(
         CrawlerTelemetryPayload::sampleCrawlers()
        ,CrawlerTelemetryPayload::sampleProcess()
        ,CrawlerTelemetryPayload::sampleQueue()
        ,CrawlerTelemetryPayload::sampleSystem()
        );
    }
}

// This is an autogenerated file:CrawlerTelemetryCrawlers

class CrawlerTelemetryCrawlers {
    private int $active; // json:active Required

    /**
     * @param int $active
     */
    public function __construct(int $active) {
        $this->active = $active;
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromActive(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toActive(): int {
        if (CrawlerTelemetryCrawlers::validateActive($this->active))  {
            return $this->active; /*int*/
        }
        throw new Exception('never get to this CrawlerTelemetryCrawlers::active');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateActive(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:CrawlerTelemetryCrawlers::active");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getActive(): int {
        if (CrawlerTelemetryCrawlers::validateActive($this->active))  {
            return $this->active;
        }
        throw new Exception('never get to getActive CrawlerTelemetryCrawlers::active');
    }

    /**
     * @return int
     */
    public static function sampleActive(): int {
        return 31; /*31:active*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return CrawlerTelemetryCrawlers::validateActive($this->active);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'active'} = $this->toActive();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return CrawlerTelemetryCrawlers
     * @throws Exception
     */
    public static function from(stdClass $obj): CrawlerTelemetryCrawlers {
        return new CrawlerTelemetryCrawlers(
         CrawlerTelemetryCrawlers::fromActive($obj->{'active'})
        );
    }

    /**
     * @return CrawlerTelemetryCrawlers
     */
    public static function sample(): CrawlerTelemetryCrawlers {
        return new CrawlerTelemetryCrawlers(
         CrawlerTelemetryCrawlers::sampleActive()
        );
    }
}

// This is an autogenerated file:CrawlerTelemetryProcess

class CrawlerTelemetryProcess {
    private CrawlerTelemetryMemory $memory; // json:memory Required
    private int $pid; // json:pid Required
    private float $uptime; // json:uptime Required

    /**
     * @param CrawlerTelemetryMemory $memory
     * @param int $pid
     * @param float $uptime
     */
    public function __construct(CrawlerTelemetryMemory $memory, int $pid, float $uptime) {
        $this->memory = $memory;
        $this->pid = $pid;
        $this->uptime = $uptime;
    }

    /**
     * @param stdClass $value
     * @throws Exception
     * @return CrawlerTelemetryMemory
     */
    public static function fromMemory(stdClass $value): CrawlerTelemetryMemory {
        return CrawlerTelemetryMemory::from($value); /*class*/
    }

    /**
     * @throws Exception
     * @return stdClass
     */
    public function toMemory(): stdClass {
        if (CrawlerTelemetryProcess::validateMemory($this->memory))  {
            return $this->memory->to(); /*class*/
        }
        throw new Exception('never get to this CrawlerTelemetryProcess::memory');
    }

    /**
     * @param CrawlerTelemetryMemory
     * @return bool
     * @throws Exception
     */
    public static function validateMemory(CrawlerTelemetryMemory $value): bool {
        $value->validate();
        return true;
    }

    /**
     * @throws Exception
     * @return CrawlerTelemetryMemory
     */
    public function getMemory(): CrawlerTelemetryMemory {
        if (CrawlerTelemetryProcess::validateMemory($this->memory))  {
            return $this->memory;
        }
        throw new Exception('never get to getMemory CrawlerTelemetryProcess::memory');
    }

    /**
     * @return CrawlerTelemetryMemory
     */
    public static function sampleMemory(): CrawlerTelemetryMemory {
        return CrawlerTelemetryMemory::sample(); /*31:memory*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function frompid(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function topid(): int {
        if (CrawlerTelemetryProcess::validatepid($this->pid))  {
            return $this->pid; /*int*/
        }
        throw new Exception('never get to this CrawlerTelemetryProcess::pid');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validatepid(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:CrawlerTelemetryProcess::pid");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getpid(): int {
        if (CrawlerTelemetryProcess::validatepid($this->pid))  {
            return $this->pid;
        }
        throw new Exception('never get to getpid CrawlerTelemetryProcess::pid');
    }

    /**
     * @return int
     */
    public static function samplepid(): int {
        return 32; /*32:pid*/
    }

    /**
     * @param float $value
     * @throws Exception
     * @return float
     */
    public static function fromUptime(float $value): float {
        return $value; /*float*/
    }

    /**
     * @throws Exception
     * @return float
     */
    public function toUptime(): float {
        if (CrawlerTelemetryProcess::validateUptime($this->uptime))  {
            return $this->uptime; /*float*/
        }
        throw new Exception('never get to this CrawlerTelemetryProcess::uptime');
    }

    /**
     * @param float
     * @return bool
     * @throws Exception
     */
    public static function validateUptime(float $value): bool {
        if (!is_float($value) && !is_int($value)) {
            throw new Exception("Attribute Error:CrawlerTelemetryProcess::uptime");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return float
     */
    public function getUptime(): float {
        if (CrawlerTelemetryProcess::validateUptime($this->uptime))  {
            return $this->uptime;
        }
        throw new Exception('never get to getUptime CrawlerTelemetryProcess::uptime');
    }

    /**
     * @return float
     */
    public static function sampleUptime(): float {
        return 33.033; /*33:uptime*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return CrawlerTelemetryProcess::validateMemory($this->memory)
        || CrawlerTelemetryProcess::validatepid($this->pid)
        || CrawlerTelemetryProcess::validateUptime($this->uptime);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'memory'} = $this->toMemory();
        $out->{'pid'} = $this->topid();
        $out->{'uptime'} = $this->toUptime();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return CrawlerTelemetryProcess
     * @throws Exception
     */
    public static function from(stdClass $obj): CrawlerTelemetryProcess {
        return new CrawlerTelemetryProcess(
         CrawlerTelemetryProcess::fromMemory($obj->{'memory'})
        ,CrawlerTelemetryProcess::frompid($obj->{'pid'})
        ,CrawlerTelemetryProcess::fromUptime($obj->{'uptime'})
        );
    }

    /**
     * @return CrawlerTelemetryProcess
     */
    public static function sample(): CrawlerTelemetryProcess {
        return new CrawlerTelemetryProcess(
         CrawlerTelemetryProcess::sampleMemory()
        ,CrawlerTelemetryProcess::samplepid()
        ,CrawlerTelemetryProcess::sampleUptime()
        );
    }
}

// This is an autogenerated file:CrawlerTelemetryMemory

class CrawlerTelemetryMemory {
    private int $heapTotal; // json:heapTotal Required
    private int $heapUsed; // json:heapUsed Required
    private int $rss; // json:rss Required

    /**
     * @param int $heapTotal
     * @param int $heapUsed
     * @param int $rss
     */
    public function __construct(int $heapTotal, int $heapUsed, int $rss) {
        $this->heapTotal = $heapTotal;
        $this->heapUsed = $heapUsed;
        $this->rss = $rss;
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromHeapTotal(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toHeapTotal(): int {
        if (CrawlerTelemetryMemory::validateHeapTotal($this->heapTotal))  {
            return $this->heapTotal; /*int*/
        }
        throw new Exception('never get to this CrawlerTelemetryMemory::heapTotal');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateHeapTotal(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:CrawlerTelemetryMemory::heapTotal");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getHeapTotal(): int {
        if (CrawlerTelemetryMemory::validateHeapTotal($this->heapTotal))  {
            return $this->heapTotal;
        }
        throw new Exception('never get to getHeapTotal CrawlerTelemetryMemory::heapTotal');
    }

    /**
     * @return int
     */
    public static function sampleHeapTotal(): int {
        return 31; /*31:heapTotal*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromHeapUsed(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toHeapUsed(): int {
        if (CrawlerTelemetryMemory::validateHeapUsed($this->heapUsed))  {
            return $this->heapUsed; /*int*/
        }
        throw new Exception('never get to this CrawlerTelemetryMemory::heapUsed');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateHeapUsed(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:CrawlerTelemetryMemory::heapUsed");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getHeapUsed(): int {
        if (CrawlerTelemetryMemory::validateHeapUsed($this->heapUsed))  {
            return $this->heapUsed;
        }
        throw new Exception('never get to getHeapUsed CrawlerTelemetryMemory::heapUsed');
    }

    /**
     * @return int
     */
    public static function sampleHeapUsed(): int {
        return 32; /*32:heapUsed*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromrss(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function torss(): int {
        if (CrawlerTelemetryMemory::validaterss($this->rss))  {
            return $this->rss; /*int*/
        }
        throw new Exception('never get to this CrawlerTelemetryMemory::rss');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validaterss(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:CrawlerTelemetryMemory::rss");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getrss(): int {
        if (CrawlerTelemetryMemory::validaterss($this->rss))  {
            return $this->rss;
        }
        throw new Exception('never get to getrss CrawlerTelemetryMemory::rss');
    }

    /**
     * @return int
     */
    public static function samplerss(): int {
        return 33; /*33:rss*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return CrawlerTelemetryMemory::validateHeapTotal($this->heapTotal)
        || CrawlerTelemetryMemory::validateHeapUsed($this->heapUsed)
        || CrawlerTelemetryMemory::validaterss($this->rss);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'heapTotal'} = $this->toHeapTotal();
        $out->{'heapUsed'} = $this->toHeapUsed();
        $out->{'rss'} = $this->torss();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return CrawlerTelemetryMemory
     * @throws Exception
     */
    public static function from(stdClass $obj): CrawlerTelemetryMemory {
        return new CrawlerTelemetryMemory(
         CrawlerTelemetryMemory::fromHeapTotal($obj->{'heapTotal'})
        ,CrawlerTelemetryMemory::fromHeapUsed($obj->{'heapUsed'})
        ,CrawlerTelemetryMemory::fromrss($obj->{'rss'})
        );
    }

    /**
     * @return CrawlerTelemetryMemory
     */
    public static function sample(): CrawlerTelemetryMemory {
        return new CrawlerTelemetryMemory(
         CrawlerTelemetryMemory::sampleHeapTotal()
        ,CrawlerTelemetryMemory::sampleHeapUsed()
        ,CrawlerTelemetryMemory::samplerss()
        );
    }
}

// This is an autogenerated file:CrawlerTelemetryQueue

class CrawlerTelemetryQueue {
    private int $active; // json:active Required
    private int $waiting; // json:waiting Required

    /**
     * @param int $active
     * @param int $waiting
     */
    public function __construct(int $active, int $waiting) {
        $this->active = $active;
        $this->waiting = $waiting;
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromActive(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toActive(): int {
        if (CrawlerTelemetryQueue::validateActive($this->active))  {
            return $this->active; /*int*/
        }
        throw new Exception('never get to this CrawlerTelemetryQueue::active');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateActive(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:CrawlerTelemetryQueue::active");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getActive(): int {
        if (CrawlerTelemetryQueue::validateActive($this->active))  {
            return $this->active;
        }
        throw new Exception('never get to getActive CrawlerTelemetryQueue::active');
    }

    /**
     * @return int
     */
    public static function sampleActive(): int {
        return 31; /*31:active*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromWaiting(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toWaiting(): int {
        if (CrawlerTelemetryQueue::validateWaiting($this->waiting))  {
            return $this->waiting; /*int*/
        }
        throw new Exception('never get to this CrawlerTelemetryQueue::waiting');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateWaiting(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:CrawlerTelemetryQueue::waiting");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getWaiting(): int {
        if (CrawlerTelemetryQueue::validateWaiting($this->waiting))  {
            return $this->waiting;
        }
        throw new Exception('never get to getWaiting CrawlerTelemetryQueue::waiting');
    }

    /**
     * @return int
     */
    public static function sampleWaiting(): int {
        return 32; /*32:waiting*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return CrawlerTelemetryQueue::validateActive($this->active)
        || CrawlerTelemetryQueue::validateWaiting($this->waiting);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'active'} = $this->toActive();
        $out->{'waiting'} = $this->toWaiting();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return CrawlerTelemetryQueue
     * @throws Exception
     */
    public static function from(stdClass $obj): CrawlerTelemetryQueue {
        return new CrawlerTelemetryQueue(
         CrawlerTelemetryQueue::fromActive($obj->{'active'})
        ,CrawlerTelemetryQueue::fromWaiting($obj->{'waiting'})
        );
    }

    /**
     * @return CrawlerTelemetryQueue
     */
    public static function sample(): CrawlerTelemetryQueue {
        return new CrawlerTelemetryQueue(
         CrawlerTelemetryQueue::sampleActive()
        ,CrawlerTelemetryQueue::sampleWaiting()
        );
    }
}

// This is an autogenerated file:CrawlerTelemetrySystem

class CrawlerTelemetrySystem {
    private int $freeMemory; // json:freeMemory Required
    private array $loadAverage; // json:loadAverage Required
    private int $totalMemory; // json:totalMemory Required

    /**
     * @param int $freeMemory
     * @param array $loadAverage
     * @param int $totalMemory
     */
    public function __construct(int $freeMemory, array $loadAverage, int $totalMemory) {
        $this->freeMemory = $freeMemory;
        $this->loadAverage = $loadAverage;
        $this->totalMemory = $totalMemory;
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromFreeMemory(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toFreeMemory(): int {
        if (CrawlerTelemetrySystem::validateFreeMemory($this->freeMemory))  {
            return $this->freeMemory; /*int*/
        }
        throw new Exception('never get to this CrawlerTelemetrySystem::freeMemory');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateFreeMemory(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:CrawlerTelemetrySystem::freeMemory");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getFreeMemory(): int {
        if (CrawlerTelemetrySystem::validateFreeMemory($this->freeMemory))  {
            return $this->freeMemory;
        }
        throw new Exception('never get to getFreeMemory CrawlerTelemetrySystem::freeMemory');
    }

    /**
     * @return int
     */
    public static function sampleFreeMemory(): int {
        return 31; /*31:freeMemory*/
    }

    /**
     * @param array $value
     * @throws Exception
     * @return array
     */
    public static function fromLoadAverage(array $value): array {
        return  array_map(function ($value) {
            return $value; /*float*/
        }, $value);
    }

    /**
     * @throws Exception
     * @return array
     */
    public function toLoadAverage(): array {
        if (CrawlerTelemetrySystem::validateLoadAverage($this->loadAverage))  {
            return array_map(function ($value) {
                return $value; /*float*/
            }, $this->loadAverage);
        }
        throw new Exception('never get to this CrawlerTelemetrySystem::loadAverage');
    }

    /**
     * @param array
     * @return bool
     * @throws Exception
     */
    public static function validateLoadAverage(array $value): bool {
        if (!is_array($value)) {
            throw new Exception("Attribute Error:CrawlerTelemetrySystem::loadAverage");
        }
        array_walk($value, function($value_v) {
            if (!is_float($value_v) && !is_int($value_v)) {
                throw new Exception("Attribute Error:CrawlerTelemetrySystem::loadAverage");
            }
        });
        return true;
    }

    /**
     * @throws Exception
     * @return array
     */
    public function getLoadAverage(): array {
        if (CrawlerTelemetrySystem::validateLoadAverage($this->loadAverage))  {
            return $this->loadAverage;
        }
        throw new Exception('never get to getLoadAverage CrawlerTelemetrySystem::loadAverage');
    }

    /**
     * @return array
     */
    public static function sampleLoadAverage(): array {
        return  array(
            32.032 /*32:*/
        ); /* 32:loadAverage*/
    }

    /**
     * @param int $value
     * @throws Exception
     * @return int
     */
    public static function fromTotalMemory(int $value): int {
        return $value; /*int*/
    }

    /**
     * @throws Exception
     * @return int
     */
    public function toTotalMemory(): int {
        if (CrawlerTelemetrySystem::validateTotalMemory($this->totalMemory))  {
            return $this->totalMemory; /*int*/
        }
        throw new Exception('never get to this CrawlerTelemetrySystem::totalMemory');
    }

    /**
     * @param int
     * @return bool
     * @throws Exception
     */
    public static function validateTotalMemory(int $value): bool {
        if (!is_integer($value)) {
            throw new Exception("Attribute Error:CrawlerTelemetrySystem::totalMemory");
        }
        return true;
    }

    /**
     * @throws Exception
     * @return int
     */
    public function getTotalMemory(): int {
        if (CrawlerTelemetrySystem::validateTotalMemory($this->totalMemory))  {
            return $this->totalMemory;
        }
        throw new Exception('never get to getTotalMemory CrawlerTelemetrySystem::totalMemory');
    }

    /**
     * @return int
     */
    public static function sampleTotalMemory(): int {
        return 33; /*33:totalMemory*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return CrawlerTelemetrySystem::validateFreeMemory($this->freeMemory)
        || CrawlerTelemetrySystem::validateLoadAverage($this->loadAverage)
        || CrawlerTelemetrySystem::validateTotalMemory($this->totalMemory);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'freeMemory'} = $this->toFreeMemory();
        $out->{'loadAverage'} = $this->toLoadAverage();
        $out->{'totalMemory'} = $this->toTotalMemory();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return CrawlerTelemetrySystem
     * @throws Exception
     */
    public static function from(stdClass $obj): CrawlerTelemetrySystem {
        return new CrawlerTelemetrySystem(
         CrawlerTelemetrySystem::fromFreeMemory($obj->{'freeMemory'})
        ,CrawlerTelemetrySystem::fromLoadAverage($obj->{'loadAverage'})
        ,CrawlerTelemetrySystem::fromTotalMemory($obj->{'totalMemory'})
        );
    }

    /**
     * @return CrawlerTelemetrySystem
     */
    public static function sample(): CrawlerTelemetrySystem {
        return new CrawlerTelemetrySystem(
         CrawlerTelemetrySystem::sampleFreeMemory()
        ,CrawlerTelemetrySystem::sampleLoadAverage()
        ,CrawlerTelemetrySystem::sampleTotalMemory()
        );
    }
}

// This is an autogenerated file:CrawlerTelemetryType

class CrawlerTelemetryType {
    public static CrawlerTelemetryType $CRAWLER_TELEMETRY;
    public static function init() {
        CrawlerTelemetryType::$CRAWLER_TELEMETRY = new CrawlerTelemetryType('crawler.telemetry');
    }
    private string $enum;
    public function __construct(string $enum) {
        $this->enum = $enum;
    }

    /**
     * @param CrawlerTelemetryType
     * @return string
     * @throws Exception
     */
    public static function to(CrawlerTelemetryType $obj): string {
        switch ($obj->enum) {
            case CrawlerTelemetryType::$CRAWLER_TELEMETRY->enum: return 'crawler.telemetry';
        }
        throw new Exception('the give value is not an enum-value.');
    }

    /**
     * @param mixed
     * @return CrawlerTelemetryType
     * @throws Exception
     */
    public static function from($obj): CrawlerTelemetryType {
        switch ($obj) {
            case 'crawler.telemetry': return CrawlerTelemetryType::$CRAWLER_TELEMETRY;
        }
        throw new Exception("Cannot deserialize CrawlerTelemetryType");
    }

    /**
     * @return CrawlerTelemetryType
     */
    public static function sample(): CrawlerTelemetryType {
        return CrawlerTelemetryType::$CRAWLER_TELEMETRY;
    }
}
CrawlerTelemetryType::init();
