#!/usr/bin/env node
import { execFileSync } from 'node:child_process';
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptsDir = path.dirname(fileURLToPath(import.meta.url));
const packageDir = path.join(scriptsDir, '..');
const schemaDir = path.join(packageDir, 'schema');
const tsOutDir = path.join(packageDir, 'node', 'types');
const phpOutDir = path.join(packageDir, 'php', 'Value');
const quicktypeBin = path.join(packageDir, 'node_modules', '.bin', 'quicktype');
const phpNamespace = 'EqualSite\\Events';
const phpValueNamespace = `${phpNamespace}\\Value`;

const pascalCase = (name) =>
    name
        .split('-')
        .map((part) => part[0].toUpperCase() + part.slice(1))
        .join('');

const schemaFiles = readdirSync(schemaDir).filter((file) => file.endsWith('.json'));

if (schemaFiles.length === 0) {
    console.log('No schema files found in packages/events/schema — nothing to generate yet.');
    process.exit(0);
}

mkdirSync(tsOutDir, { recursive: true });
mkdirSync(phpOutDir, { recursive: true });

const eventTypeEntries = [];

for (const file of schemaFiles) {
    const name = path.basename(file, '.json');
    const schemaPath = path.join(schemaDir, file);
    const className = pascalCase(name);

    const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));
    const eventType = schema.properties?.type?.enum?.[0];
    if (typeof eventType !== 'string') {
        throw new Error(
            `Schema ${file} has no properties.type.enum[0] string — Bus needs this to map ` +
            'the event type to its generated PHP class. Fix the schema before regenerating.',
        );
    }
    eventTypeEntries.push({ eventType, className });

    execFileSync(
        quicktypeBin,
        ['-s', 'schema', schemaPath, '-o', path.join(tsOutDir, `${name}.ts`), '-l', 'typescript', '--just-types'],
        { stdio: 'inherit' },
    );

    // quicktype's PHP target has no --namespace flag (that option only exists for Ruby),
    // so the namespace declaration is injected below after generation.
    const phpOutFile = path.join(phpOutDir, `${className}.php`);

    execFileSync(
        quicktypeBin,
        [
            '-s', 'schema', schemaPath,
            '-o', phpOutFile,
            '-l', 'php',
            '--acronym-style', 'original',
        ],
        { stdio: 'inherit' },
    );

    // quicktype's PHP output references stdClass/Exception unqualified, relying on them
    // resolving to the global namespace. Once we inject a namespace declaration, PHP no
    // longer falls back to the global namespace for bare class names — only functions and
    // constants get that fallback — so these `use` imports are required, not cosmetic.
    const phpSource = readFileSync(phpOutFile, 'utf8');
    writeFileSync(
        phpOutFile,
        phpSource.replace(
            /^<\?php\n/,
            `<?php\n\nnamespace ${phpValueNamespace};\n\nuse Exception;\nuse stdClass;\n`,
        ),
    );
}

// Emit the type-string <-> PHP-class mapping Bus.php needs for dispatch (Bus::listen() and
// Bus::consume()). Generated here (not hand-maintained) so it can never drift from the schemas.
// Lives directly under php/ (not php/Value/) alongside Bus.php/Subscriber.php; map entries
// reference `Value\ClassName` relative to the `EqualSite\Events` namespace declared below.
const eventTypeMapPath = path.join(packageDir, 'php', 'EventTypeMap.php');
const mapEntries = eventTypeEntries
    .map(({ eventType, className }) => `        '${eventType}' => Value\\${className}::class,`)
    .join('\n');

writeFileSync(
    eventTypeMapPath,
    `<?php

namespace ${phpNamespace};

// This is an autogenerated file — generated by packages/events/scripts/generate.mjs.
// Do not edit by hand; edit the schema files under packages/events/schema instead.

final class EventTypeMap
{
    /** @var array<string, class-string> */
    public const MAP = [
${mapEntries}
    ];

    public static function classFor(string $type): ?string
    {
        return self::MAP[$type] ?? null;
    }

    public static function typeFor(string $class): ?string
    {
        static $reverse = null;
        if ($reverse === null) {
            $reverse = array_flip(self::MAP);
        }
        return $reverse[$class] ?? null;
    }
}
`,
);

console.log(`Generated ${schemaFiles.length} event type(s) into node/types/ and php/Value/ (+ EventTypeMap.php).`);
