<?php

namespace EqualSite\Events;

// This is an autogenerated file — generated by packages/events/scripts/generate.mjs.
// Do not edit by hand; edit the schema files under packages/events/schema instead.

final class EventTypeMap
{
    /** @var array<string, class-string> */
    public const MAP = [
        'audit.cancelled' => Value\AuditCancelled::class,
        'audit.completed' => Value\AuditCompleted::class,
        'audit.failed' => Value\AuditFailed::class,
        'audit.page.completed' => Value\AuditPageCompleted::class,
        'audit.page.failed' => Value\AuditPageFailed::class,
        'audit.page.skipped' => Value\AuditPageSkipped::class,
        'audit.page.started' => Value\AuditPageStarted::class,
        'audit.progress' => Value\AuditProgress::class,
        'audit.queued' => Value\AuditQueued::class,
        'audit.started' => Value\AuditStarted::class,
        'crawler.telemetry' => Value\CrawlerTelemetry::class,
    ];

    public static function classFor(string $type): ?string
    {
        return self::MAP[$type] ?? null;
    }

    public static function typeFor(string $class): ?string
    {
        static $reverse = null;
        if ($reverse === null) {
            $reverse = array_flip(self::MAP);
        }
        return $reverse[$class] ?? null;
    }
}
